<?php
$array = array(
	'adder' => array(
		'name' => 'Adder',
		'brand' => 'Truffade',
		'model' => 'adder',
		'price' => 280000,
		'category' => 'super',
		'hash' => `adder`,
		'shop' => 'pdm',
	),
	'alpha' => array(
		'name' => 'Alpha',
		'brand' => 'Albany',
		'model' => 'alpha',
		'price' => 53000,
		'category' => 'sports',
		'hash' => `alpha`,
		'shop' => 'pdm',
	),
	'ardent' => array(
		'name' => 'Ardent',
		'brand' => 'Ocelot',
		'model' => 'ardent',
		'price' => 30000,
		'category' => 'sportsclassics',
		'hash' => `ardent`,
		'shop' => 'pdm',
	),
	'asea' => array(
		'name' => 'Asea',
		'brand' => 'Declasse',
		'model' => 'asea',
		'price' => 2500,
		'category' => 'sedans',
		'hash' => `asea`,
		'shop' => 'pdm',
	),
	'autarch' => array(
		'name' => 'Autarch',
		'brand' => 'Överflöd',
		'model' => 'autarch',
		'price' => 224000,
		'category' => 'super',
		'hash' => `autarch`,
		'shop' => 'pdm',
	),
	'avarus' => array(
		'name' => 'Avarus',
		'brand' => 'LCC',
		'model' => 'avarus',
		'price' => 20000,
		'category' => 'motorcycles',
		'hash' => `avarus`,
		'shop' => 'pdm',
	),
	'bagger' => array(
		'name' => 'Bagger',
		'brand' => 'WMC',
		'model' => 'bagger',
		'price' => 13500,
		'category' => 'motorcycles',
		'hash' => `bagger`,
		'shop' => 'pdm',
	),
	'baller2' => array(
		'name' => 'Baller',
		'brand' => 'Gallivanter',
		'model' => 'baller2',
		'price' => 15000,
		'category' => 'suvs',
		'hash' => `baller2`,
		'shop' => 'pdm',
	),
	'baller3' => array(
		'name' => 'Baller LE',
		'brand' => 'Gallivanter',
		'model' => 'baller3',
		'price' => 15000,
		'category' => 'suvs',
		'hash' => `baller3`,
		'shop' => 'pdm',
	),
	'banshee' => array(
		'name' => 'Banshee',
		'brand' => 'Bravado',
		'model' => 'banshee',
		'price' => 56000,
		'category' => 'sports',
		'hash' => `banshee`,
		'shop' => 'pdm',
	),
	'banshee2' => array(
		'name' => 'Banshee 900R',
		'brand' => 'Bravado',
		'model' => 'banshee2',
		'price' => 120000,
		'category' => 'super',
		'hash' => `banshee2`,
		'shop' => 'pdm',
	),
	'bati' => array(
		'name' => 'Bati 801',
		'brand' => 'Pegassi',
		'model' => 'bati',
		'price' => 24000,
		'category' => 'motorcycles',
		'hash' => `bati`,
		'shop' => 'pdm',
	),
	'bestiagts' => array(
		'name' => 'Bestia GTS',
		'brand' => 'Grotti',
		'model' => 'bestiagts',
		'price' => 37000,
		'category' => 'sports',
		'hash' => `bestiagts`,
		'shop' => 'pdm',
	),
	'bfinjection' => array(
		'name' => 'Bf Injection', 
		'brand' => 'Annis',
		'price' => 9000,
		'category' => 'offroad',
		'model' => 'bfinjection',
		'hash' => `bfinjection`,
		'shop' => 'pdm',
	),
	'bifta' => array(
		'name' => 'Bifta', 
		'brand' => 'Annis',
		'price' => 15500,
		'category' => 'offroad',
		'model' => 'bifta',
		'hash' => `bifta`,
		'shop' => 'pdm',
	),
	'bison' => array(
		'name' => 'Bison',
		'brand' => 'Bravado',
		'model' => 'bison',
		'price' => 18000,
		'category' => 'vans',
		'hash' => `bison`,
		'shop' => 'pdm',
	),
	'bjxl' => array(
		'name' => 'BeeJay XL',
		'brand' => 'Karin',
		'model' => 'bjxl',
		'price' => 19000,
		'category' => 'suvs',
		'hash' => `bjxl`,
		'shop' => 'pdm',
	),
	'blade' => array(
		'name' => 'Blade',
		'brand' => 'Vapid',
		'model' => 'blade',
		'price' => 23500,
		'category' => 'muscle',
		'hash' => `blade`,
		'shop' => 'pdm',
	),
	'blazer' => array(
		'name' => 'Blazer', 
		'price' => 7500,
		'category' => 'offroad',
		'model' => 'blazer',
		'hash' => `blazer`,
		'shop' => 'pdm',
	),
	'blazer4' => array(
		'name' => 'Blazer Sport',
		'brand' => 'Annis',
		'price' => 9250,
		'category' => 'offroad',
		'model' => 'blazer4',
		'hash' => `blazer4`,
		'shop' => 'pdm',
	),
	'blista' => array(
		'name' => 'Blista',
		'brand' => 'Dinka',
		'model' => 'blista',
		'price' => 13000,
		'category' => 'compacts',
		'hash' => `blista`,
		'shop' => 'pdm',
	),
	'blista2' => array(
		'name' => 'Blista Compact',
		'brand' => 'Dinka',
		'model' => 'blista2',
		'price' => 18950,
		'category' => 'compacts',
		'hash' => `blista2`,
		'shop' => 'pdm',
	),
	'bobcatxl' => array(
		'name' => 'Bobcat XL Open',
		'brand' => 'Vapid',
		'model' => 'bobcatxl',
		'price' => 13500,
		'category' => 'vans',
		'hash' => `bobcatxl`,
		'shop' => 'pdm',
	),
	'brawler' => array(
		'name' => 'Brawler', 
		'brand' => 'Annis',
		'price' => 40000,
		'category' => 'offroad',
		'model' => 'brawler',
		'hash' => `brawler`,
		'shop' => 'pdm',
	),
	'brioso' => array(
		'name' => 'Brioso R/A',
		'brand' => 'Grotti',
		'model' => 'brioso',
		'price' => 20000,
		'category' => 'compacts',
		'hash' => `brioso`,
		'shop' => 'pdm',
	),
	'btype' => array(              //meme car that goes pretty fast 
		'name' => 'Roosevelt',
		'brand' => 'Albany',
		'model' => 'btype',
		'price' => 75000,
		'category' => 'sportsclassics',
		'hash' => `btype`,
		'shop' => 'pdm',
	),
	'btype2' => array(
		'name' => 'Franken Stange',
		'brand' => 'Albany',
		'model' => 'btype2',
		'price' => 87000,
		'category' => 'sportsclassics',
		'hash' => `btype2`,
		'shop' => 'pdm',
	),
	'btype3' => array(
		'name' => 'Roosevelt Valor',
		'brand' => 'Albany',
		'model' => 'btype3',
		'price' => 63000,
		'category' => 'sportsclassics',
		'hash' => `btype3`,
		'shop' => 'pdm',
	),
	'buccaneer' => array(
		'name' => 'Buccaneer',
		'brand' => 'Albany',
		'model' => 'buccaneer',
		'price' => 22500,
		'category' => 'muscle',
		'hash' => `buccaneer`,
		'shop' => 'pdm',
	),
	'buccaneer2' => array(
		'name' => 'Buccaneer Rider',
		'brand' => 'Albany',
		'model' => 'buccaneer2',
		'price' => 24500,
		'category' => 'muscle',
		'hash' => `buccaneer2`,
		'shop' => 'pdm',
	),
	'buffalo' => array(
		'name' => 'Buffalo',
		'brand' => 'Bravado',
		'model' => 'buffalo',
		'price' => 18750,
		'category' => 'sports',
		'hash' => `buffalo`,
		'shop' => 'pdm',
	),
	'buffalo2' => array(
		'name' => 'Buffalo S',
		'brand' => 'Bravado',
		'model' => 'buffalo2',
		'price' => 24500,
		'category' => 'sports',
		'hash' => `buffalo2`,
		'shop' => 'pdm',
	),
	'bullet' => array(
		'name' => 'Bullet',
		'brand' => 'Vapid',
		'model' => 'bullet',
		'price' => 120000,
		'category' => 'super',
		'hash' => `bullet`,
		'shop' => 'pdm',
	),
	'burrito3' => array(
		'name' => 'Burrito',
		'brand' => 'Declasse',
		'model' => 'burrito3',
		'price' => 4000,
		'category' => 'vans',
		'hash' => `burrito3`,
		'shop' => 'pdm',
	),
	'gburrito2' => array(
		'name' => 'Burrito Custom',
		'brand' => 'Declasse',
		'model' => 'gburrito2',
		'price' => 11500,
		'category' => 'vans',
		'hash' => `gburrito2`,
		'shop' => 'pdm',
	),
	'carbonizzare' => array(
		'name' => 'Carbonizzare',
		'brand' => 'Grotti',
		'model' => 'carbonizzare',
		'price' => 155000,
		'category' => 'sports',
		'hash' => `carbonizzare`,
		'shop' => 'pdm',
	),
	'carbonrs' => array(
		'name' => 'Carbon RS',
		'brand' => 'Nagasaki',
		'model' => 'carbonrs',
		'price' => 22000,
		'category' => 'motorcycles',
		'hash' => `carbonrs`,
		'shop' => 'pdm',
	),
	'casco' => array(
		'name' => 'Casco',
		'brand' => 'Lampadati',
		'model' => 'casco',
		'price' => 100000,
		'category' => 'sportsclassics',
		'hash' => `casco`,
		'shop' => 'pdm',
	),
	'cavalcade2' => array(
		'name' => 'Cavalcade',
		'brand' => 'Albany',
		'model' => 'cavalcade2',
		'price' => 16500,
		'category' => 'suvs',
		'hash' => `cavalcade2`,
		'shop' => 'pdm',
	),
	'cheetah' => array(
		'name' => 'Cheetah',
		'brand' => 'Grotti',
		'model' => 'cheetah',
		'price' => 214000,
		'category' => 'super',
		'hash' => `cheetah`,
		'shop' => 'pdm',
	),
	'cheetah2' => array(
		'name' => 'Cheetah Classic',
		'brand' => 'Grotti',
		'model' => 'cheetah2',
		'price' => 195000,
		'category' => 'sports',
		'hash' => `cheetah2`,
		'shop' => 'pdm',
	),
	'chimera' => array(
		'name' => 'Chimera',
		'brand' => 'Nagasaki',
		'model' => 'chimera',
		'price' => 21000,
		'category' => 'motorcycles',
		'hash' => `chimera`,
		'shop' => 'pdm',
	),
	'chino' => array(
		'name' => 'Chino',
		'brand' => 'Vapid',
		'model' => 'chino',
		'price' => 5000,
		'category' => 'muscle',
		'hash' => `chino`,
		'shop' => 'pdm',
	),
	'chino2' => array(
		'name' => 'Chino Luxe',
		'brand' => 'Vapid',
		'model' => 'chino2',
		'price' => 8000,
		'category' => 'muscle',
		'hash' => `chino2`,
		'shop' => 'pdm',
	),
	'cogcabrio' => array(
		'name' => 'Cognoscenti Cabrio',
		'brand' => 'Enus',
		'model' => 'cogcabrio',
		'price' => 30000,
		'category' => 'coupes',
		'hash' => `cogcabrio`,
		'shop' => 'pdm',
	),
	'cognoscenti' => array(
		'name' => 'Cognoscenti',
		'brand' => 'Enus',
		'model' => 'cognoscenti',
		'price' => 22500,
		'category' => 'sedans',
		'hash' => `cognoscenti`,
		'shop' => 'pdm',
	),
	'comet2' => array(
		'name' => 'Comet',
		'brand' => 'Pfister',
		'model' => 'comet2',
		'price' => 130000,
		'category' => 'sports',
		'hash' => `comet2`,
		'shop' => 'pdm',
	),
	'comet3' => array(
		'name' => 'Comet Retro Custom',
		'brand' => 'Pfister',
		'model' => 'comet3',
		'price' => 175000,
		'category' => 'sports',
		'hash' => `comet3`,
		'shop' => 'pdm',
	),
	'comet5' => array(
		'name' => 'Comet SR',
		'brand' => 'Pfister',
		'model' => 'comet5',
		'price' => 155000,
		'category' => 'sports',
		'hash' => `comet5`,
		'shop' => 'pdm',
	),
	'coquette' => array(
		'name' => 'Coquette',
		'brand' => 'Invetero',
		'model' => 'coquette',
		'price' => 145000,
		'category' => 'sports',
		'hash' => `coquette`,
		'shop' => 'pdm',
	),
	'coquette2' => array(
		'name' => 'Coquette Classic',
		'brand' => 'Invetero',
		'model' => 'coquette2',
		'price' => 165000,
		'category' => 'sportsclassics',
		'hash' => `coquette2`,
		'shop' => 'pdm',
	),
	'coquette3' => array(
		'name' => 'Coquette BlackFin',
		'brand' => 'Invetero',
		'model' => 'coquette3',
		'price' => 180000,
		'category' => 'muscle',
		'hash' => `coquette3`,
		'shop' => 'pdm',
	),
	'cyclone' => array(         //might be too overpowered 
		'name' => 'Cyclone',
		'brand' => 'Coil',
		'model' => 'cyclone',
		'price' => 300000,
		'category' => 'super',
		'hash' => `cyclone`,
		'shop' => 'pdm',
	),
	'daemon' => array(
		'name' => 'Daemon',
		'brand' => 'WMC',
		'model' => 'daemon',
		'price' => 14000,
		'category' => 'motorcycles',
		'hash' => `daemon`,
		'shop' => 'pdm',
	),
	'defiler' => array(
		'name' => 'Defiler',
		'brand' => 'Shitzu',
		'model' => 'defiler',
		'price' => 30000,
		'category' => 'motorcycles',
		'hash' => `defiler`,
		'shop' => 'pdm',
	),
	'dilettante' => array(
		'name' => 'Dilettante',
		'brand' => 'Karin',
		'model' => 'dilettante',
		'price' => 9000,
		'category' => 'compacts',
		'hash' => `dilettante`,
		'shop' => 'pdm',
	),
	'dominator' => array(
		'name' => 'Dominator',
		'brand' => 'Vapid',
		'model' => 'dominator',
		'price' => 62500,
		'category' => 'muscle',
		'hash' => `dominator`,
		'shop' => 'pdm',
	),
	'dubsta2' => array(
		'name' => 'Dubsta Luxuary',
		'brand' => 'Benefactor',
		'model' => 'dubsta2',
		'price' => 19500,
		'category' => 'suvs',
		'hash' => `dubsta2`,
		'shop' => 'pdm',
	),
	'dubsta3' => array(
		'name' => 'Dubsta 6x6', 
		'brand' => 'Annis',
		'price' => 34000,
		'category' => 'offroad',
		'model' => 'dubsta3',
		'hash' => `dubsta3`,
		'shop' => 'pdm',
	),
	'dukes' => array(
		'name' => 'Dukes',
		'brand' => 'Imponte',
		'model' => 'dukes',
		'price' => 23500,
		'category' => 'muscle',
		'hash' => `dukes`,
		'shop' => 'pdm',
	),
	'dune' => array(
		'name' => 'Dune Buggy', 
		'brand' => 'Annis',
		'price' => 14000,
		'category' => 'offroad',
		'model' => 'dune',
		'hash' => `dune`,
		'shop' => 'pdm',
	),
	'elegy' => array(
		'name' => 'Elegy Retro Custom',
		'brand' => 'Annis',
		'model' => 'elegy',
		'price' => 145000,
		'category' => 'sports',
		'hash' => `elegy`,
		'shop' => 'pdm',
	),
	'elegy2' => array(
		'name' => 'Elegy RH8',
		'brand' => 'Annis',
		'model' => 'elegy2',
		'price' => 150000,
		'category' => 'sports',
		'hash' => `elegy2`,
		'shop' => 'pdm',
	),
	'ellie' => array(
		'name' => 'Ellie',
		'brand' => 'Vapid',
		'model' => 'ellie',
		'price' => 42250,
		'category' => 'muscle',
		'hash' => `ellie`,
		'shop' => 'pdm',
	),
	'emperor' => array(
		'name' => 'Emperor',
		'brand' => 'Albany',
		'model' => 'emperor',
		'price' => 4250,
		'category' => 'sedans',
		'hash' => `emperor`,
		'shop' => 'pdm',
	),
	'entity2' => array(
		'name' => 'Entity XXR',
		'brand' => 'Överflöd',
		'model' => 'entity2',
		'price' => 164000,
		'category' => 'super',
		'hash' => `entity2`,
		'shop' => 'pdm',
	),
	'entityxf' => array(
		'name' => 'Entity XF',
		'brand' => 'Överflöd',
		'model' => 'entityxf',
		'price' => 180000,
		'category' => 'super',
		'hash' => `entityxf`,
		'shop' => 'pdm',
	),
	'esskey' => array(
		'name' => 'Esskey',
		'brand' => 'Pegassi',
		'model' => 'esskey',
		'price' => 12000,
		'category' => 'motorcycles',
		'hash' => `esskey`,
		'shop' => 'pdm',
	),
	'exemplar' => array(
		'name' => 'Exemplar',
		'brand' => 'Dewbauchee',
		'model' => 'exemplar',
		'price' => 40000,
		'category' => 'coupes',
		'hash' => `exemplar`,
		'shop' => 'pdm',
	),
	'f620' => array(
		'name' => 'F620',
		'brand' => 'Ocelot',
		'model' => 'f620',
		'price' => 32500,
		'category' => 'coupes',
		'hash' => `f620`,
		'shop' => 'pdm',
	),
	'faction' => array(
		'name' => 'Faction',
		'brand' => 'Willard',
		'model' => 'faction',
		'price' => 17000,
		'category' => 'muscle',
		'hash' => `faction`,
		'shop' => 'pdm',
	),
	'faction2' => array(
		'name' => 'Faction Rider',
		'brand' => 'Willard',
		'model' => 'faction2',
		'price' => 19000,
		'category' => 'muscle',
		'hash' => `faction2`,
		'shop' => 'pdm',
	),
	'fagaloa' => array(
		'name' => 'Fagaloa',
		'brand' => 'Vulcar',
		'model' => 'fagaloa',
		'price' => 13000,
		'category' => 'sportsclassics',
		'hash' => `fagaloa`,
		'shop' => 'pdm',
	),
	'faggio' => array(
		'name' => 'Faggio Sport',
		'brand' => 'Pegassi',
		'model' => 'faggio',
		'price' => 2000,
		'category' => 'motorcycles',
		'hash' => `faggio`,
		'shop' => 'pdm',
	),
	'faggio3' => array(
		'name' => 'Faggio Mod',
		'brand' => 'Pegassi',
		'model' => 'faggio3',
		'price' => 2500,
		'category' => 'motorcycles',
		'hash' => `faggio3`,
		'shop' => 'pdm',
	),
	'felon' => array(
		'name' => 'Felon',
		'brand' => 'Lampadati',
		'model' => 'felon',
		'price' => 31000,
		'category' => 'coupes',
		'hash' => `felon`,
		'shop' => 'pdm',
	),
	'felon2' => array(
		'name' => 'Felon GT',
		'brand' => 'Lampadati',
		'model' => 'felon2',
		'price' => 37000,
		'category' => 'coupes',
		'hash' => `felon2`,
		'shop' => 'pdm',
	),
	'feltzer2' => array(
		'name' => 'Feltzer',
		'brand' => 'Benefactor',
		'model' => 'feltzer2',
		'price' => 97000,
		'category' => 'sports',
		'hash' => `feltzer2`,
		'shop' => 'pdm',
	),
	'feltzer3' => array(
		'name' => 'Stirling GT',
		'brand' => 'Benefactor',
		'model' => 'feltzer3',
		'price' => 115000,
		'category' => 'sportsclassics',
		'hash' => `feltzer3`,
		'shop' => 'pdm',
	),
	'flashgt' => array(
		'name' => 'Flash GT',
		'brand' => 'Vapid',
		'model' => 'flashgt',
		'price' => 48000,
		'category' => 'sports',
		'hash' => `flashgt`,
		'shop' => 'pdm',
	),
	'fmj' => array(
		'name' => 'FMJ',
		'brand' => 'Vapid',
		'model' => 'fmj',
		'price' => 125000,
		'category' => 'super',
		'hash' => `fmj`,
		'shop' => 'pdm',
	),
	'fq2' => array(
		'name' => 'FQ2',
		'brand' => 'Fathom',
		'model' => 'fq2',
		'price' => 18500,
		'category' => 'suvs',
		'hash' => `fq2`,
		'shop' => 'pdm',
	),
	'fugitive' => array(
		'name' => 'Fugitive',
		'brand' => 'Cheval',
		'model' => 'fugitive',
		'price' => 20000,
		'category' => 'sedans',
		'hash' => `fugitive`,
		'shop' => 'pdm',
	),
	'furoregt' => array(
		'name' => 'Furore GT',
		'brand' => 'Lampadati',
		'model' => 'furoregt',
		'price' => 78000,
		'category' => 'sports',
		'hash' => `furoregt`,
		'shop' => 'pdm',
	),
	'futo' => array(
		'name' => 'Futo',
		'brand' => 'Karin',
		'model' => 'futo',
		'price' => 17500,
		'category' => 'coupes',
		'hash' => `futo`,
		'shop' => 'pdm',
	),
	'gauntlet' => array(
		'name' => 'Gauntlet',
		'brand' => 'Bravado',
		'model' => 'gauntlet',
		'price' => 28500,
		'category' => 'muscle',
		'hash' => `gauntlet`,
		'shop' => 'pdm',
	),
	'glendale' => array(
		'name' => 'Glendale',
		'brand' => 'Benefactor',
		'model' => 'glendale',
		'price' => 3400,
		'category' => 'sedans',
		'hash' => `glendale`,
		'shop' => 'pdm',
	),
	'gp1' => array(
		'name' => 'GP1',
		'brand' => 'Progen',
		'model' => 'gp1',
		'price' => 110000,
		'category' => 'super',
		'hash' => `gp1`,
		'shop' => 'pdm',
	),
	'granger' => array(
		'name' => 'Granger',
		'brand' => 'Declasse',
		'model' => 'granger',
		'price' => 22000,
		'category' => 'suvs',
		'hash' => `granger`,
		'shop' => 'pdm',
	),
	'gresley' => array(
		'name' => 'Gresley',
		'brand' => 'Bravado',
		'model' => 'gresley',
		'price' => 25000,
		'category' => 'suvs',
		'hash' => `gresley`,
		'shop' => 'pdm',
	),
	'gt500' => array(
		'name' => 'GT500',
		'brand' => 'Grotti',
		'model' => 'gt500',
		'price' => 130000,
		'category' => 'sportsclassics',
		'hash' => `gt500`,
		'shop' => 'pdm',
	),
	'guardian' => array(
		'name' => 'Guardian', 
		'brand' => 'Annis',
		'price' => 21000,
		'category' => 'offroad',
		'model' => 'guardian',
		'hash' => `guardian`,
		'shop' => 'pdm',
	),
	'hakuchou' => array(
		'name' => 'Hakuchou',
		'brand' => 'Shitzu',
		'model' => 'hakuchou',
		'price' => 17000,
		'category' => 'motorcycles',
		'hash' => `hakuchou`,
		'shop' => 'pdm',
	),
	'hexer' => array(
		'name' => 'Hexer',
		'brand' => 'LCC',
		'model' => 'hexer',
		'price' => 16000,
		'category' => 'motorcycles',
		'hash' => `hexer`,
		'shop' => 'pdm',
	),
	'hotknife' => array(
		'name' => 'Hotknife',
		'brand' => 'Vapid',
		'model' => 'hotknife',
		'price' => 90000,
		'category' => 'muscle',
		'hash' => `hotknife`,
		'shop' => 'pdm',
	),
	'huntley' => array(
		'name' => 'Huntley S',
		'brand' => 'Enus',
		'model' => 'huntley',
		'price' => 24500,
		'category' => 'suvs',
		'hash' => `huntley`,
		'shop' => 'pdm',
	),
	'hustler' => array(
		'name' => 'Hustler',
		'brand' => 'Vapid',
		'model' => 'hustler',
		'price' => 95000,
		'category' => 'muscle',
		'hash' => `hustler`,
		'shop' => 'pdm',
	),
	'infernus' => array(
		'name' => 'Infernus',
		'brand' => 'Pegassi',
		'model' => 'infernus',
		'price' => 235000,
		'category' => 'super',
		'hash' => `infernus`,
		'shop' => 'pdm',
	),
	'infernus2' => array(         
		'name' => 'Infernus Classic',
		'brand' => 'Pegassi',
		'model' => 'infernus2',
		'price' => 245000,
		'category' => 'sportsclassics',
		'hash' => `infernus2`,
		'shop' => 'pdm',
	),
	'intruder' => array(
		'name' => 'Intruder',
		'brand' => 'Karin',
		'model' => 'intruder',
		'price' => 11250,
		'category' => 'sedans',
		'hash' => `intruder`,
		'shop' => 'pdm',
	),
	'issi2' => array(
		'name' => 'Issi',
		'brand' => 'Weeny',
		'model' => 'issi2',
		'price' => 7000,
		'category' => 'compacts',
		'hash' => `issi2`,
		'shop' => 'pdm',
	),
	'issi3' => array(
		'name' => 'Issi Classic',
		'brand' => 'Weeny',
		'model' => 'issi3',
		'price' => 5000,
		'category' => 'compacts',
		'hash' => `issi3`,
		'shop' => 'pdm',
	),
	'italigtb' => array(
		'name' => 'Itali GTB',
		'brand' => 'Progen',
		'model' => 'italigtb',
		'price' => 170000,
		'category' => 'super',
		'hash' => `italigtb`,
		'shop' => 'pdm',
	),
	'jackal' => array(
		'name' => 'Jackal',
		'brand' => 'Ocelot',
		'model' => 'jackal',
		'price' => 19000,
		'category' => 'coupes',
		'hash' => `jackal`,
		'shop' => 'pdm',
	),
	'jester' => array(
		'name' => 'Jester',
		'brand' => 'Dinka',
		'model' => 'jester',
		'price' => 132250,
		'category' => 'sports',
		'hash' => `jester`,
		'shop' => 'pdm',
	),
	'jester3' => array(
		'name' => 'Jester Classic',
		'brand' => 'Dinka',
		'model' => 'jester3',
		'price' => 85000,
		'category' => 'sports',
		'hash' => `jester3`,
		'shop' => 'pdm',
	),
	'khamelion' => array(
		'name' => 'Khamelion',
		'brand' => 'Hijak',
		'model' => 'khamelion',
		'price' => 90000,
		'category' => 'sports',
		'hash' => `khamelion`,
		'shop' => 'pdm',
	),
	'kuruma' => array(
		'name' => 'Kuruma',
		'brand' => 'Karin',
		'model' => 'kuruma',
		'price' => 72000,
		'category' => 'sports',
		'hash' => `kuruma`,
		'shop' => 'pdm',
	),
	'landstalker' => array(
		'name' => 'Landstalker',
		'brand' => 'Dundreary',
		'model' => 'landstalker',
		'price' => 12000,
		'category' => 'suvs',
		'hash' => `landstalker`,
		'shop' => 'pdm',
	),
	'lynx' => array(
		'name' => 'Lynx',
		'brand' => 'Ocelot',
		'model' => 'lynx',
		'price' => 150000,
		'category' => 'sports',
		'hash' => `lynx`,
		'shop' => 'pdm',
	),
	'mamba' => array(
		'name' => 'Mamba',
		'brand' => 'Declasse',
		'model' => 'mamba',
		'price' => 140000,
		'category' => 'sportsclassics',
		'hash' => `mamba`,
		'shop' => 'pdm',
	),
	'massacro' => array(
		'name' => 'Massacro',
		'brand' => 'Dewbauchee',
		'model' => 'massacro',
		'price' => 110000,
		'category' => 'sports',
		'hash' => `massacro`,
		'shop' => 'pdm',
	),
	'monroe' => array(
		'name' => 'Monroe',
		'brand' => 'Pegassi',
		'model' => 'monroe',
		'price' => 115000,
		'category' => 'sportsclassics',
		'hash' => `monroe`,
		'shop' => 'pdm',
	),
	'moonbeam' => array(
		'name' => 'Moonbeam',
		'brand' => 'Declasse',
		'model' => 'moonbeam',
		'price' => 13000,
		'category' => 'vans',
		'hash' => `moonbeam`,
		'shop' => 'pdm',
	),
	'nemesis' => array(
		'name' => 'Nemesis',
		'brand' => 'Principe',
		'model' => 'nemesis',
		'price' => 20000,
		'category' => 'motorcycles',
		'hash' => `nemesis`,
		'shop' => 'pdm',
	),
	'neon' => array(
		'name' => 'Neon',
		'brand' => 'Pfister',
		'model' => 'neon',
		'price' => 220000,
		'category' => 'sports',
		'hash' => `neon`,
		'shop' => 'pdm',
	),
	'nero' => array(
		'name' => 'Nero',
		'brand' => 'Truffade',
		'model' => 'nero',
		'price' => 200000,
		'category' => 'super',
		'hash' => `nero`,
		'shop' => 'pdm',
	),
	'nightblade' => array(
		'name' => 'Nightblade',
		'brand' => 'WMC',
		'model' => 'nightblade',
		'price' => 23000,
		'category' => 'motorcycles',
		'hash' => `nightblade`,
		'shop' => 'pdm',
	),
	'nightshade' => array(
		'name' => 'Nightshade',
		'brand' => 'Imponte',
		'model' => 'nightshade',
		'price' => 70000,
		'category' => 'muscle',
		'hash' => `nightshade`,
		'shop' => 'pdm',
	),
	'ninef' => array(
		'name' => '9F',
		'brand' => 'Obey',
		'model' => 'ninef',
		'price' => 95000,
		'category' => 'sports',
		'hash' => `ninef`,
		'shop' => 'pdm',
	),
	'ninef2' => array(
		'name' => '9F Cabrio',
		'brand' => 'Obey',
		'model' => 'ninef2',
		'price' => 105000,
		'category' => 'sports',
		'hash' => `ninef2`,
		'shop' => 'pdm',
	),
	'omnis' => array(
		'name' => 'Omnis',
		'brand' => 'Wow',
		'model' => 'omnis',
		'price' => 90000,
		'category' => 'sports',
		'hash' => `omnis`,
		'shop' => 'pdm',
	),
	'oracle' => array(
		'name' => 'Oracle',
		'brand' => 'Ubermacht',
		'model' => 'oracle',
		'price' => 22000,
		'category' => 'sedans',
		'hash' => `oracle`,
		'shop' => 'pdm',
	),
	'oracle2' => array(
		'name' => 'Oracle XS',
		'brand' => 'Übermacht',
		'model' => 'oracle2',
		'price' => 28000,
		'category' => 'coupes',
		'hash' => `oracle2`,
		'shop' => 'pdm',
	),
	'osiris' => array(
		'name' => 'Osiris',
		'brand' => 'Pegassi',
		'model' => 'osiris',
		'price' => 220000,
		'category' => 'super',
		'hash' => `osiris`,
		'shop' => 'pdm',
	),
	'panto' => array(
		'name' => 'Panto',
		'brand' => 'Benefactor',
		'model' => 'panto',
		'price' => 3200,
		'category' => 'compacts',
		'hash' => `panto`,
		'shop' => 'pdm',
	),
	'pariah' => array(
		'name' => 'Pariah',
		'brand' => 'Ocelot',
		'model' => 'pariah',
		'price' => 90000,
		'category' => 'sports',
		'hash' => `pariah`,
		'shop' => 'pdm',
	),
	'patriot' => array(
		'name' => 'Patriot',
		'brand' => 'Mammoth',
		'model' => 'patriot',
		'price' => 21000,
		'category' => 'suvs',
		'hash' => `patriot`,
		'shop' => 'pdm',
	),
	'pcj' => array(
		'name' => 'PCJ-600',
		'brand' => 'Shitzu',
		'model' => 'pcj',
		'price' => 15000,
		'category' => 'motorcycles',
		'hash' => `pcj`,
		'shop' => 'pdm',
	),
	'penetrator' => array(
		'name' => 'Penetrator',
		'brand' => 'Ocelot',
		'model' => 'penetrator',
		'price' => 130000,
		'category' => 'super',
		'hash' => `penetrator`,
		'shop' => 'pdm',
	),
	'pfister811' => array(
		'name' => '811',
		'brand' => 'Pfister',
		'model' => 'pfister811',
		'price' => 220000,
		'category' => 'super',
		'hash' => `pfister811`,
		'shop' => 'pdm',
	),
	'phoenix' => array(
		'name' => 'Phoenix',
		'brand' => 'Imponte',
		'model' => 'phoenix',
		'price' => 65000,
		'category' => 'muscle',
		'hash' => `phoenix`,
		'shop' => 'pdm',
	),
	'picador' => array(
		'name' => 'Picador',
		'brand' => 'Cheval',
		'model' => 'picador',
		'price' => 20000,
		'category' => 'muscle',
		'hash' => `picador`,
		'shop' => 'pdm',
	),
	'pigalle' => array(
		'name' => 'Pigalle',
		'brand' => 'Lampadati',
		'model' => 'pigalle',
		'price' => 92000,
		'category' => 'sportsclassics',
		'hash' => `pigalle`,
		'shop' => 'pdm',
	),
	'prairie' => array(
		'name' => 'Prairie',
		'brand' => 'Bollokan',
		'model' => 'prairie',
		'price' => 30000,
		'category' => 'compacts',
		'hash' => `prairie`,
		'shop' => 'pdm',
	),
	'premier' => array(
		'name' => 'Premier',
		'brand' => 'Declasse',
		'model' => 'premier',
		'price' => 12000,
		'category' => 'sedans',
		'hash' => `premier`,
		'shop' => 'pdm',
	),
	'primo2' => array(
		'name' => 'Primo Custom',
		'brand' => 'Albany',
		'model' => 'primo2',
		'price' => 14500,
		'category' => 'sedans',
		'hash' => `primo2`,
		'shop' => 'pdm',
	),
	'prototipo' => array(
		'name' => 'X80 Proto',
		'brand' => 'Grotti',
		'model' => 'prototipo',
		'price' => 235000,
		'category' => 'super',
		'hash' => `prototipo`,
		'shop' => 'pdm',
	),
	'radi' => array(
		'name' => 'Radius',
		'brand' => 'Vapid',
		'model' => 'radi',
		'price' => 18000,
		'category' => 'suvs',
		'hash' => `radi`,
		'shop' => 'pdm',
	),
	'rapidgt' => array(
		'name' => 'Rapid GT',
		'brand' => 'Dewbauchee',
		'model' => 'rapidgt',
		'price' => 86000,
		'category' => 'sports',
		'hash' => `rapidgt`,
		'shop' => 'pdm',
	),
	'rapidgt2' => array(
		'name' => 'Rapid GT Convertible',
		'brand' => 'Dewbauchee',
		'model' => 'rapidgt2',
		'price' => 92000,
		'category' => 'sports',
		'hash' => `rapidgt2`,
		'shop' => 'pdm',
	),
	'rapidgt3' => array(
		'name' => 'Rapid GT',
		'brand' => 'Dewbauchee',
		'model' => 'rapidgt3',
		'price' => 90000,
		'category' => 'sportsclassics',
		'hash' => `rapidgt3`,
		'shop' => 'pdm',
	),
	'reaper' => array(
		'name' => 'Reaper',
		'brand' => 'Pegassi',
		'model' => 'reaper',
		'price' => 100000,
		'category' => 'super',
		'hash' => `reaper`,
		'shop' => 'pdm',
	),
	'rebel2' => array(
		'name' => 'Rebel', 
		'brand' => 'Annis',
		'model' => 'rebel2',
		'price' => 20000,
		'category' => 'offroad',
		'hash' => `rebel2`,
		'shop' => 'pdm',
	),
	'regina' => array(
		'name' => 'Regina',
		'brand' => 'Dundreary',
		'model' => 'regina',
		'price' => 7000,
		'category' => 'sedans',
		'hash' => `regina`,
		'shop' => 'pdm',
	),
	'revolter' => array(
		'name' => 'Revolter',
		'brand' => 'Ubermacht',
		'model' => 'revolter',
		'price' => 95000,
		'category' => 'sports',
		'hash' => `revolter`,
		'shop' => 'pdm',
	),
	'rhapsody' => array(
		'name' => 'Rhapsody',
		'brand' => 'Declasse',
		'model' => 'rhapsody',
		'price' => 10000,
		'category' => 'compacts',
		'hash' => `rhapsody`,
		'shop' => 'pdm',
	),
	'rocoto' => array(
		'name' => 'Rocoto',
		'brand' => 'Obey',
		'model' => 'rocoto',
		'price' => 13000,
		'category' => 'suvs',
		'hash' => `rocoto`,
		'shop' => 'pdm',
	),
	'ruffian' => array(
		'name' => 'Ruffian',
		'brand' => 'Pegassi',
		'model' => 'ruffian',
		'price' => 25000,
		'category' => 'motorcycles',
		'hash' => `ruffian`,
		'shop' => 'pdm',
	),
	'rumpo' => array(
		'name' => 'Rumpo',
		'brand' => 'Bravado',
		'model' => 'rumpo',
		'price' => 9000,
		'category' => 'vans',
		'hash' => `rumpo`,
		'shop' => 'pdm',
	),
	'ruston' => array(
		'name' => 'Ruston',
		'brand' => 'Hijak',
		'model' => 'ruston',
		'price' => 130000,
		'category' => 'sports',
		'hash' => `ruston`,
		'shop' => 'pdm',
	),
	'sabregt' => array(
		'name' => 'Sabre Turbo',
		'brand' => 'Declasse',
		'model' => 'sabregt',
		'price' => 23000,
		'category' => 'muscle',
		'hash' => `sabregt`,
		'shop' => 'pdm',
	),
	'sabregt2' => array(
		'name' => 'Sabre GT',
		'brand' => 'Declasse',
		'model' => 'sabregt2',
		'price' => 26500,
		'category' => 'muscle',
		'hash' => `sabregt2`,
		'shop' => 'pdm',
	),
	'sandking' => array(
		'name' => 'Sandking', 
		'brand' => 'Annis',
		'price' => 25000,
		'category' => 'offroad',
		'model' => 'sandking',
		'hash' => `sandking`,
		'shop' => 'pdm',
	),
	'sc1' => array(
		'name' => 'SC1',
		'brand' => 'Übermacht',
		'model' => 'sc1',
		'price' => 90000,
		'category' => 'super',
		'hash' => `sc1`,
		'shop' => 'pdm',
	),
	'schafter2' => array(
		'name' => 'Schafter',
		'brand' => 'Benefactor',
		'model' => 'schafter2',
		'price' => 16000,
		'category' => 'sedans',
		'hash' => `schafter2`,
		'shop' => 'pdm',
	),
	'schafter3' => array(
		'name' => 'Schafter V12',
		'brand' => 'Benefactor',
		'model' => 'schafter3',
		'price' => 35000,
		'category' => 'sports',
		'hash' => `schafter3`,
		'shop' => 'pdm',
	),
	'seminole' => array(
		'name' => 'Seminole',
		'brand' => 'Canis',
		'model' => 'seminole',
		'price' => 20000,
		'category' => 'suvs',
		'hash' => `seminole`,
		'shop' => 'pdm',
	),
	'sentinel' => array(
		'name' => 'Sentinel',
		'brand' => 'Übermacht',
		'model' => 'sentinel',
		'price' => 30000,
		'category' => 'coupes',
		'hash' => `sentinel`,
		'shop' => 'pdm',
	),
	'sentinel2' => array(
		'name' => 'Sentinel XS',
		'brand' => ' Übermacht',
		'model' => 'sentinel2',
		'price' => 33000,
		'category' => 'coupes',
		'hash' => `sentinel2`,
		'shop' => 'pdm',
	),
	'sentinel3' => array(
		'name' => 'Sentinel Classic',
		'brand' => 'Übermacht',
		'model' => 'sentinel3',
		'price' => 70000,
		'category' => 'coupes',
		'hash' => `sentinel3`,
		'shop' => 'pdm',
	),
	'seven70' => array(
		'name' => 'Seven-70',
		'brand' => 'Dewbauchee',
		'model' => 'seven70',
		'price' => 140000,
		'category' => 'sports',
		'hash' => `seven70`,
		'shop' => 'pdm',
	),
	'slamvan3' => array(
		'name' => 'Slam Van Custom',
		'brand' => 'Vapid',
		'model' => 'slamvan3',
		'price' => 17000,
		'category' => 'muscle',
		'hash' => `slamvan3`,
		'shop' => 'pdm',
	),
	'sovereign' => array(
		'name' => 'Sovereign',
		'brand' => 'WMC',
		'model' => 'sovereign',
		'price' => 8000,
		'category' => 'motorcycles',
		'hash' => `sovereign`,
		'shop' => 'pdm',
	),
	'specter' => array(
		'name' => 'Specter',
		'brand' => 'Dewbauchee',
		'model' => 'specter',
		'price' => 160000,
		'category' => 'sports',
		'hash' => `specter`,
		'shop' => 'pdm',
	),
	'stafford' => array(
		'name' => 'Stafford',
		'brand' => 'Enus',
		'model' => 'stafford',
		'price' => 30000,
		'category' => 'sedans',
		'hash' => `stafford`,
		'shop' => 'pdm',
	),
	'stalion' => array(
		'name' => 'Stallion',
		'brand' => 'Declasse',
		'model' => 'stalion',
		'price' => 33000,
		'category' => 'muscle',
		'hash' => `stalion`,
		'shop' => 'pdm',
	),
	'stingergt' => array(
		'name' => 'Stinger GT',
		'brand' => 'Grotti',
		'model' => 'stingergt',
		'price' => 70000,
		'category' => 'sportsclassics',
		'hash' => `stingergt`,
		'shop' => 'pdm',
	),
	'streiter' => array(
		'name' => 'Streiter',
		'brand' => 'Benefactor',
		'model' => 'streiter',
		'price' => 40000,
		'category' => 'sports',
		'hash' => `streiter`,
		'shop' => 'pdm',
	),
	'sultan' => array(
		'name' => 'Sultan',
		'brand' => 'Karin',
		'model' => 'sultan',
		'price' => 50000,
		'category' => 'sports',
		'hash' => `sultan`,
		'shop' => 'pdm',
	),
	'sultanrs' => array(
		'name' => 'Sultan RS',
		'brand' => 'Karin',
		'model' => 'sultanrs',
		'price' => 76500,
		'category' => 'sports',
		'hash' => `sultanrs`,
		'shop' => 'pdm',
	),
	'superd' => array(
		'name' => 'Super Diamond',
		'brand' => 'Enus',
		'model' => 'superd',
		'price' => 17000,
		'category' => 'sedans',
		'hash' => `superd`,
		'shop' => 'pdm',
	),
	'surano' => array(
		'name' => 'Surano',
		'brand' => ' Benefactor',
		'model' => 'surano',
		'price' => 80000,
		'category' => 'sports',
		'hash' => `surano`,
		'shop' => 'pdm',
	),
	'surge' => array(
		'name' => 'Surge',
		'brand' => 'Cheval',
		'model' => 'surge',
		'price' => 20000,
		'category' => 'sedans',
		'hash' => `surge`,
		'shop' => 'pdm',
	),
	't20' => array(
		'name' => 'T20',
		'brand' => 'Progen',
		'model' => 't20',
		'price' => 1650000,
		'category' => 'super',
		'hash' => `t20`,
		'shop' => 'pdm',
	),
	'tailgater' => array(
		'name' => 'Tailgater',
		'brand' => 'Obey',
		'model' => 'tailgater',
		'price' => 22000,
		'category' => 'sedans',
		'hash' => `tailgater`,
		'shop' => 'pdm',
	),
	'taipan' => array(
		'name' => 'Taipan',
		'brand' => 'Cheval',
		'model' => 'taipan',
		'price' => 1850000,
		'category' => 'super',
		'hash' => `taipan`,
		'shop' => 'pdm',
	),
	'tampa' => array(
		'name' => 'Tampa',
		'brand' => 'Declasse',
		'model' => 'tampa',
		'price' => 24500,
		'category' => 'muscle',
		'hash' => `tampa`,
		'shop' => 'pdm',
	),
	'tampa2' => array(
		'name' => 'Drift Tampa',
		'brand' => 'Declasse',
		'model' => 'tampa2',
		'price' => 80000,
		'category' => 'muscle',
		'hash' => `tampa2`,
		'shop' => 'pdm',
	),
	'tempesta' => array(
		'name' => 'Tempesta',
		'brand' => 'Pegassi',
		'model' => 'tempesta',
		'price' => 120000,
		'category' => 'super',
		'hash' => `tempesta`,
		'shop' => 'pdm',
	),
	'tezeract' => array(
		'name' => 'Tezeract',
		'brand' => 'Pegassi',
		'model' => 'tezeract',
		'price' => 220000,
		'category' => 'super',
		'hash' => `tezeract`,
		'shop' => 'pdm',
	),
	'thrust' => array(
		'name' => 'Thrust',
		'brand' => 'Dinka',
		'model' => 'thrust',
		'price' => 22000,
		'category' => 'motorcycles',
		'hash' => `thrust`,
		'shop' => 'pdm',
	),
	'torero' => array(
		'name' => 'Torero',
		'brand' => 'Pegassi',
		'model' => 'torero',
		'price' => 84000,
		'category' => 'sportsclassics',
		'hash' => `torero`,
		'shop' => 'pdm',
	),
	'trophytruck' => array(
		'name' => 'Trophy Truck', 
		'brand' => 'Annis',
		'price' => 60000,
		'category' => 'offroad',
		'model' => 'trophytruck',
		'hash' => `trophytruck`,
		'shop' => 'pdm',
	),
	'trophytruck2' => array(
		'name' => 'Trophy Truck Limited',
		'brand' => 'Annis',
		'price' => 80000,
		'category' => 'offroad',
		'model' => 'trophytruck2',
		'hash' => `trophytruck2`,
		'shop' => 'pdm',
	),
	'turismor' => array(
		'name' => 'Turismo R',
		'brand' => 'Grotti',
		'model' => 'turismor',
		'price' => 140000,
		'category' => 'super',
		'hash' => `turismor`,
		'shop' => 'pdm',
	),
	'tyrant' => array(
		'name' => 'Tyrant',
		'brand' => ' Överflöd',
		'model' => 'tyrant',
		'price' => 2100000,
		'category' => 'super',
		'hash' => `tyrant`,
		'shop' => 'pdm',
	),
	'vacca' => array(
		'name' => 'Vacca',
		'brand' => 'Pegassi',
		'model' => 'vacca',
		'price' => 105000,
		'category' => 'super',
		'hash' => `vacca`,
		'shop' => 'pdm',
	),
	'vagner' => array(
		'name' => 'Vagner',
		'brand' => 'Dewbauchee',
		'model' => 'vagner',
		'price' => 1660000,
		'category' => 'super',
		'hash' => `vagner`,
		'shop' => 'pdm',
	),
	'verlierer2' => array(
		'name' => 'Verlierer',
		'brand' => 'Bravado',
		'model' => 'verlierer2',
		'price' => 90500,
		'category' => 'sports',
		'hash' => `verlierer2`,
		'shop' => 'pdm',
	),
	'vigero' => array(
		'name' => 'Vigero',
		'brand' => 'Declasse',
		'model' => 'vigero',
		'price' => 39500,
		'category' => 'muscle',
		'hash' => `vigero`,
		'shop' => 'pdm',
	),
	'virgo' => array(
		'name' => 'Virgo',
		'brand' => 'Albany',
		'model' => 'virgo',
		'price' => 22000,
		'category' => 'muscle',
		'hash' => `virgo`,
		'shop' => 'pdm',
	),
	'visione' => array(
		'name' => 'Visione',
		'brand' => 'Grotti',
		'model' => 'visione',
		'price' => 750000,
		'category' => 'sports',
		'hash' => `visione`,
		'shop' => 'pdm',
	),
	'voltic' => array(
		'name' => 'Voltic',
		'brand' => 'Coil',
		'model' => 'voltic',
		'price' => 120000,
		'category' => 'super',
		'hash' => `voltic`,
		'shop' => 'pdm',
	),
	'voodoo' => array(
		'name' => 'Voodoo',
		'brand' => 'Declasse',
		'model' => 'voodoo',
		'price' => 13000,
		'category' => 'muscle',
		'hash' => `voodoo`,
		'shop' => 'pdm',
	),
	'washington' => array(
		'name' => 'Washington',
		'brand' => 'Albany',
		'model' => 'washington',
		'price' => 7000,
		'category' => 'sedans',
		'hash' => `washington`,
		'shop' => 'pdm',
	),
	'windsor' => array(
		'name' => 'Windsor',
		'brand' => 'Enus',
		'model' => 'windsor',
		'price' => 27000,
		'category' => 'coupes',
		'hash' => `windsor`,
		'shop' => 'pdm',
	),
	'windsor2' => array(
		'name' => 'Windsor Drop',
		'brand' => 'Enus',
		'model' => 'windsor2',
		'price' => 34000,
		'category' => 'coupes',
		'hash' => `windsor2`,
		'shop' => 'pdm',
	),
	'xa21' => array(
		'name' => 'XA-21',
		'brand' => 'Ocelot',
		'model' => 'xa21',
		'price' => 180000,
		'category' => 'super',
		'hash' => `xa21`,
		'shop' => 'pdm',
	),
	'xls' => array(
		'name' => 'XLS',
		'brand' => 'Benefactor',
		'model' => 'xls',
		'price' => 17000,
		'category' => 'suvs',
		'hash' => `xls`,
		'shop' => 'pdm',
	),
	'yosemite' => array(
		'name' => 'Yosemite',
		'brand' => 'Declasse',
		'model' => 'yosemite',
		'price' => 19500,
		'category' => 'muscle',
		'hash' => `yosemite`,
		'shop' => 'pdm',
	),
	'z190' => array(
		'name' => '190Z',
		'brand' => 'Karin',
		'model' => 'z190',
		'price' => 78000,
		'category' => 'sportsclassics',
		'hash' => `z190`,
		'shop' => 'pdm',
	),
	'zentorno' => array(
		'name' => 'Zentorno',
		'brand' => 'Pegassi',
		'model' => 'zentorno',
		'price' => 340000,
		'category' => 'super',
		'hash' => `zentorno`,
		'shop' => 'pdm',
	),
	'zion' => array(
		'name' => 'Zion',
		'brand' => 'Übermacht',
		'model' => 'zion',
		'price' => 22000,
		'category' => 'coupes',
		'hash' => `zion`,
		'shop' => 'pdm',
	),
	'zion2' => array(
		'name' => 'Zion Cabrio',
		'brand' => 'Übermacht',
		'model' => 'zion2',
		'price' => 28000,
		'category' => 'coupes',
		'hash' => `zion2`,
		'shop' => 'pdm',
	),
	'zombieb' => array(
		'name' => 'Zombie Chopper',
		'brand' => 'Western',
		'model' => 'zombieb',
		'price' => 27000,
		'category' => 'motorcycles',
		'hash' => `zombieb`,
		'shop' => 'pdm',
	),
	'ztype' => array(
		'name' => 'Z-Type',
		'brand' => 'Truffade',
		'model' => 'ztype',
		'price' => 270000,
		'category' => 'sportsclassics',
		'hash' => `ztype`,
		'shop' => 'pdm',
	),'akuma' => array(
		'name' => 'Akuma',
		'brand' => 'Dinka',
		'model' => 'akuma',
		'price' => 55000,
		'category' => 'motorcycles',
		'hash' => `akuma`,
		'shop' => 'pdm',
	),
	'asbo' => array(
		'name' => 'Asbo',
		'brand' => 'Maxwell',
		'model' => 'asbo',
		'price' => 4000,
		'category' => 'compacts',
		'hash' => `asbo`,
		'shop' => 'pdm',
	),
	'asterope' => array(
		'name' => 'Asterope',
		'brand' => 'Karin',
		'model' => 'asterope',
		'price' => 11000,
		'category' => 'sedans',
		'hash' => `asterope`,
		'shop' => 'pdm',
	),
	'baller' => array(
		'name' => 'Baller',
		'brand' => 'Gallivanter',
		'model' => 'baller',
		'price' => 22000,
		'category' => 'suvs',
		'hash' => `baller`,
		'shop' => 'pdm',
	),
	'baller4' => array(
		'name' => 'Baller LE LWB',
		'brand' => 'Gallivanter',
		'model' => 'baller4',
		'price' => 29000,
		'category' => 'suvs',
		'hash' => `baller4`,
		'shop' => 'pdm',
	),
	'baller5' => array(
		'name' => 'Baller LE (Armored)',
		'brand' => 'Gallivanter',
		'model' => 'baller5',
		'price' => 78000,
		'category' => 'suvs',
		'hash' => `baller5`,
		'shop' => 'pdm',
	),
	'baller6' => array(
		'name' => 'Baller LE LWB (Armored)',
		'brand' => 'Gallivanter',
		'model' => 'baller6',
		'price' => 82000,
		'category' => 'suvs',
		'hash' => `baller6`,
		'shop' => 'pdm',
	),
	'bati2' => array(
		'name' => 'Bati 801RR',
		'brand' => 'Pegassi',
		'model' => 'bati2',
		'price' => 19000,
		'category' => 'motorcycles',
		'hash' => `bati2`,
		'shop' => 'pdm',
	),
	'bf400' => array(
		'name' => 'BF400',
		'brand' => 'Nagasaki',
		'model' => 'bf400',
		'price' => 22000,
		'category' => 'motorcycles',
		'hash' => `bf400`,
		'shop' => 'pdm',
	),
	'blazer2' => array(
		'name' => 'Blazer Lifeguard',
		'brand' => 'Nagasaki',
		'model' => 'blazer2',
		'price' => 7000,
		'category' => 'offroad',
		'hash' => `blazer2`,
		'shop' => 'pdm',
	),
	'blazer3' => array(
		'name' => 'Blazer Hot Rod',
		'brand' => 'Nagasaki',
		'model' => 'blazer3',
		'price' => 7000,
		'category' => 'offroad',
		'hash' => `blazer3`,
		'shop' => 'pdm',
	),
	'blazer5' => array(
		'name' => 'Blazer Aqua',
		'brand' => 'Nagasaki',
		'model' => 'blazer5',
		'price' => 40000,
		'category' => 'offroad',
		'hash' => `blazer5`,
		'shop' => 'pdm',
	),
	'blista3' => array(
		'name' => 'Blista Go Go Monkey',
		'brand' => 'Dinka',
		'model' => 'blista3',
		'price' => 15000,
		'category' => 'compacts',
		'hash' => `blista3`,
		'shop' => 'pdm',
	),
	'bmx' => array(
		'name' => 'BMX',
		'model' => 'bmx',
		'price' => 160,
		'category' => 'cycles',
		'hash' => `bmx`,
		'shop' => 'pdm',
	),
	'brioso2' => array(
		'name' => 'Brioso 300',
		'brand' => 'Grotti',
		'model' => 'brioso2',
		'price' => 12000,
		'category' => 'compacts',
		'hash' => `brioso2`,
		'shop' => 'pdm',
	),
	'caracara' => array(
		'name' => 'Caracara',
		'brand' => 'Vapid',
		'model' => 'caracara',
		'price' => 60000,
		'category' => 'offroad',
		'hash' => `caracara`,
		'shop' => 'pdm',
	),
	'caracara2' => array(
		'name' => 'Caracara 4x4',
		'brand' => 'Vapid',
		'model' => 'caracara2',
		'price' => 80000,
		'category' => 'offroad',
		'hash' => `caracara2`,
		'shop' => 'pdm',
	),
	'cavalcade' => array(
		'name' => 'Cavalcade',
		'brand' => 'Albany',
		'model' => 'cavalcade',
		'price' => 14000,
		'category' => 'suvs',
		'hash' => `cavalcade`,
		'shop' => 'pdm',
	),
	'cheburek' => array(
		'name' => 'Cheburek',
		'brand' => 'Rune',
		'model' => 'cheburek',
		'price' => 7000,
		'category' => 'sportsclassic',
		'hash' => `cheburek`,
		'shop' => 'pdm',
	),
	'cliffhanger' => array(
		'name' => 'Cliffhanger',
		'brand' => 'Western',
		'model' => 'cliffhanger',
		'price' => 28500,
		'category' => 'motorcycles',
		'hash' => `cliffhanger`,
		'shop' => 'pdm',
	),
	'clique' => array(
		'name' => 'Clique',
		'brand' => 'Vapid',
		'model' => 'clique',
		'price' => 20000,
		'category' => 'muscle',
		'hash' => `clique`,
		'shop' => 'pdm',
	),
	'club' => array(
		'name' => 'Club',
		'brand' => 'BF',
		'model' => 'club',
		'price' => 8000,
		'category' => 'compacts',
		'hash' => `club`,
		'shop' => 'pdm',
	),
	'cog55' => array(
		'name' => 'Cognoscenti 55',
		'brand' => 'Enus',
		'model' => 'cog55',
		'price' => 22000,
		'category' => 'sedans',
		'hash' => `cog55`,
		'shop' => 'pdm',
	),
	'comet4' => array(
		'name' => 'Comet Safari',
		'brand' => 'Pfister',
		'model' => 'comet4',
		'price' => 110000,
		'category' => 'sports',
		'hash' => `comet4`,
		'shop' => 'pdm',
	),
	'contender' => array(
		'name' => 'Contender',
		'brand' => 'Vapid',
		'model' => 'contender',
		'price' => 35000,
		'category' => 'suvs',
		'hash' => `contender`,
		'shop' => 'pdm',
	),
	'coquette4' => array(
		'name' => 'Coquette D10',
		'brand' => 'Invetero',
		'model' => 'coquette4',
		'price' => 220000,
		'category' => 'sports',
		'hash' => `coquette4`,
		'shop' => 'pdm',
	),
	'cruiser' => array(
		'name' => 'Cruiser',
		'model' => 'cruiser',
		'price' => 510,
		'category' => 'cycles',
		'hash' => `cruiser`,
		'shop' => 'pdm',
	),
	'daemon2' => array(
		'name' => 'Daemon Custom',
		'brand' => 'Western',
		'model' => 'daemon2',
		'price' => 23000,
		'category' => 'motorcycles',
		'hash' => `daemon2`,
		'shop' => 'pdm',
	),
	'deluxo' => array(
		'name' => 'Deluxo',
		'brand' => 'Imponte',
		'model' => 'deluxo',
		'price' => 55000,
		'category' => 'sportsclassic',
		'hash' => `deluxo`,
		'shop' => 'pdm',
	),
	'deveste' => array(
		'name' => 'Deveste',
		'brand' => 'Principe',
		'model' => 'deveste',
		'price' => 234000,
		'category' => 'super',
		'hash' => `deveste`,
		'shop' => 'pdm',
	),
	'deviant' => array(
		'name' => 'Deviant',
		'brand' => 'Schyster',
		'model' => 'deviant',
		'price' => 70000,
		'category' => 'muscle',
		'hash' => `deviant`,
		'shop' => 'pdm',
	),
	'diablous' => array(
		'name' => 'Diablous',
		'brand' => 'Principe',
		'model' => 'diablous',
		'price' => 30000,
		'category' => 'motorcycles',
		'hash' => `diablous`,
		'shop' => 'pdm',
	),
	'diablous2' => array(
		'name' => 'Diablous Custom',
		'brand' => 'Principe',
		'model' => 'diablous2',
		'price' => 38000,
		'category' => 'motorcycles',
		'hash' => `diablous2`,
		'shop' => 'pdm',
	),
	'dilettante2' => array(
		'name' => 'Dilettante Patrol',
		'brand' => 'Karin',
		'model' => 'dilettante2',
		'price' => 12000,
		'category' => 'compacts',
		'hash' => `dilettante2`,
		'shop' => 'pdm',
	),
	'dominator2' => array(
		'name' => 'Pißwasser Dominator',
		'brand' => 'Vapid',
		'model' => 'dominator2',
		'price' => 50000,
		'category' => 'muscle',
		'hash' => `dominator2`,
		'shop' => 'pdm',
	),
	'dominator3' => array(
		'name' => 'Dominator GTX',
		'brand' => 'Vapid',
		'model' => 'dominator3',
		'price' => 70000,
		'category' => 'muscle',
		'hash' => `dominator3`,
		'shop' => 'pdm',
	),
	'dominator4' => array(
		'name' => 'Dominator Arena',
		'brand' => 'Vapid',
		'model' => 'dominator4',
		'price' => 200000,
		'category' => 'muscle',
		'hash' => `dominator4`,
		'shop' => 'pdm',
	),
	'double' => array(
		'name' => 'Double-T',
		'brand' => 'Dinka',
		'model' => 'double',
		'price' => 28000,
		'category' => 'motorcycles',
		'hash' => `double`,
		'shop' => 'pdm',
	),
	'drafter' => array(     
		'name' => '8F Drafter',
		'brand' => 'Obey',
		'model' => 'drafter',
		'price' => 80000,
		'category' => 'sports',
		'hash' => `drafter`,
		'shop' => 'pdm',
	),
	'dubsta' => array(
		'name' => 'Dubsta',
		'brand' => 'Benefactor',
		'model' => 'dubsta',
		'price' => 19000,
		'category' => 'suvs',
		'hash' => `dubsta`,
		'shop' => 'pdm',
	),
	'dukes2' => array(
		'name' => 'Dukes Nightrider',
		'brand' => 'Imponte',
		'model' => 'dukes2',
		'price' => 60000,
		'category' => 'muscle',
		'hash' => `dukes2`,
		'shop' => 'pdm',
	),
	'dukes3' => array(
		'name' => 'Beater Dukes',
		'brand' => 'Imponte',
		'model' => 'dukes3',
		'price' => 45000,
		'category' => 'muscle',
		'hash' => `dukes3`,
		'shop' => 'pdm',
	),
	'dynasty' => array(
		'name' => 'Dynasty',
		'brand' => 'Weeny',
		'model' => 'dynasty',
		'price' => 25000,
		'category' => 'sportsclassic',
		'hash' => `dynasty`,
		'shop' => 'pdm',
	),
	'emerus' => array(
		'name' => 'Emerus',
		'brand' => 'Progen',
		'model' => 'emerus',
		'price' => 220000,
		'category' => 'super',
		'hash' => `emerus`,
		'shop' => 'pdm',
	),
	'enduro' => array(
		'name' => 'Enduro',
		'brand' => 'Dinka',
		'model' => 'enduro',
		'price' => 5500,
		'category' => 'motorcycles',
		'hash' => `enduro`,
		'shop' => 'pdm',
	),
	'everon' => array(
		'name' => 'Everon',
		'brand' => 'Karin',
		'model' => 'everon',
		'price' => 60000,
		'category' => 'offroad',
		'hash' => `everon`,
		'shop' => 'pdm',
	),
	'faction3' => array(
		'name' => 'Faction Custom Donk',
		'brand' => 'Willard',
		'model' => 'faction3',
		'price' => 35000,
		'category' => 'muscle',
		'hash' => `faction3`,
		'shop' => 'pdm',
	),
	'faggio2' => array(
		'name' => 'Faggio',
		'brand' => 'Pegassi',
		'model' => 'faggio2',
		'price' => 1900,
		'category' => 'motorcycles',
		'hash' => `faggio2`,
		'shop' => 'pdm',
	),
	'fcr' => array(
		'name' => 'FCR 1000',
		'brand' => 'Pegassi',
		'model' => 'fcr',
		'price' => 5000,
		'category' => 'motorcycles',
		'hash' => `fcr`,
		'shop' => 'pdm',
	),
	'fcr2' => array(
		'name' => 'FCR 1000 Custom',
		'brand' => 'Pegassi',
		'model' => 'fcr2',
		'price' => 19000,
		'category' => 'motorcycles',
		'hash' => `fcr2`,
		'shop' => 'pdm',
	),
	'fixter' => array(
		'name' => 'Fixter',
		'model' => 'fixter',
		'price' => 225,
		'category' => 'cycles',
		'hash' => `fixter`,
		'shop' => 'pdm',
	),
	'freecrawler' => array(
		'name' => 'Freecrawler',
		'brand' => 'Canis',
		'model' => 'freecrawler',
		'price' => 24000,
		'category' => 'offroad',
		'hash' => `freecrawler`,
		'shop' => 'pdm',
	),
	'furia' => array(
		'name' => 'Furia',
		'brand' => 'Grotti',
		'model' => 'furia',
		'price' => 230000,
		'category' => 'super',
		'hash' => `furia`,
		'shop' => 'pdm',
	),
	'gargoyle' => array(
		'name' => 'Gargoyle',
		'brand' => 'Western',
		'model' => 'gargoyle',
		'price' => 32000,
		'category' => 'motorcycles',
		'hash' => `gargoyle`,
		'shop' => 'pdm',
	),
	'gauntlet2' => array(
		'name' => 'Redwood Gauntlet',
		'brand' => 'Bravado',
		'model' => 'gauntlet2',
		'price' => 70000,
		'category' => 'muscle',
		'hash' => `gauntlet2`,
		'shop' => 'pdm',
	),
	'gauntlet3' => array(
		'name' => 'Classic Gauntlet',
		'brand' => 'Bravado',
		'model' => 'gauntlet3',
		'price' => 75000,
		'category' => 'muscle',
		'hash' => `gauntlet3`,
		'shop' => 'pdm',
	),
	'gauntlet4' => array(
		'name' => 'Gauntlet Hellfire',
		'brand' => 'Bravado',
		'model' => 'gauntlet4',
		'price' => 80000,
		'category' => 'muscle',
		'hash' => `gauntlet4`,
		'shop' => 'pdm',
	),
	'gauntlet5' => array(
		'name' => 'Gauntlet Classic Custom',
		'brand' => 'Bravado',
		'model' => 'gauntlet5',
		'price' => 120000,
		'category' => 'muscle',
		'hash' => `gauntlet5`,
		'shop' => 'pdm',
	),
	'gb200' => array(
		'name' => 'GB 200',
		'brand' => 'Vapid',
		'model' => 'gb200',
		'price' => 140000,
		'category' => 'sports',
		'hash' => `gb200`,
		'shop' => 'pdm',
	),
	'glendale2' => array(
		'name' => 'Glendale',
		'brand' => 'Benefactor',
		'model' => 'glendale2',
		'price' => 12000,
		'category' => 'sedans',
		'hash' => `glendale2`,
		'shop' => 'pdm',
	),
	'habanero' => array(
		'name' => 'Habanero',
		'brand' => 'Emperor',
		'model' => 'habanero',
		'price' => 20000,
		'category' => 'suvs',
		'hash' => `habanero`,
		'shop' => 'pdm',
	),
	'hakuchou2' => array(
		'name' => 'Hakuchou Drag',
		'brand' => 'Shitzu',
		'model' => 'hakuchou2',
		'price' => 45000,
		'category' => 'motorcycles',
		'hash' => `hakuchou2`,
		'shop' => 'pdm',
	),
	'hellion' => array(
		'name' => 'Hellion',
		'brand' => 'Annis',
		'model' => 'hellion',
		'price' => 38000,
		'category' => 'offroad',
		'hash' => `hellion`,
		'shop' => 'pdm',
	),
	'hermes' => array(
		'name' => 'Hermes',
		'brand' => 'Albany',
		'model' => 'hermes',
		'price' => 535000,
		'category' => 'muscle',
		'hash' => `hermes`,
		'shop' => 'pdm',
	),
	'imorgon' => array(
		'name' => 'Imorgon',
		'brand' => 'Overflod',
		'model' => 'imorgon',
		'price' => 120000,
		'category' => 'sports',
		'hash' => `imorgon`,
		'shop' => 'pdm',
	),
	'ingot' => array(
		'name' => 'Ingot',
		'brand' => 'Vulcar',
		'model' => 'ingot',
		'price' => 4999,
		'category' => 'sedans',
		'hash' => `ingot`,
		'shop' => 'pdm',
	),
	'innovation' => array(
		'name' => 'Innovation',
		'brand' => 'LLC',
		'model' => 'innovation',
		'price' => 33500,
		'category' => 'motorcycles',
		'hash' => `innovation`,
		'shop' => 'pdm',
	),
	'issi4' => array(
		'name' => 'Issi Arena',
		'brand' => 'Weeny',
		'model' => 'issi4',
		'price' => 80000,
		'category' => 'compacts',
		'hash' => `issi4`,
		'shop' => 'pdm',
	),
	'issi7' => array(
		'name' => 'Issi Sport',
		'brand' => 'Weeny',
		'model' => 'issi7',
		'price' => 100000,
		'category' => 'compacts',
		'hash' => `issi7`,
		'shop' => 'pdm',
	),
	'italigtb2' => array(
		'name' => 'Itali GTB',
		'brand' => 'Progen',
		'model' => 'italigtb2',
		'price' => 250000,
		'category' => 'super',
		'hash' => `italigtb2`,
		'shop' => 'pdm',
	),
	'italigto' => array(
		'name' => 'Itali GTO',
		'brand' => 'Progen',
		'model' => 'italigto',
		'price' => 260000,
		'category' => 'sports',
		'hash' => `italigto`,
		'shop' => 'pdm',
	),
	'italirsx' => array(
		'name' => 'Itali RSX',
		'brand' => 'Progen',
		'model' => 'italirsx',
		'price' => 260000,
		'category' => 'sports',
		'hash' => `italirsx`,
		'shop' => 'pdm',
	),
	'jb700' => array(
		'name' => 'JB 700',
		'brand' => 'Dewbauchee',
		'model' => 'jb700',
		'price' => 240000,
		'category' => 'sportsclassic',
		'hash' => `jb700`,
		'shop' => 'pdm',
	),
	'jb7002' => array(
		'name' => 'JB 700W',
		'brand' => 'Dewbauchee',
		'model' => 'jb7002',
		'price' => 40000,
		'category' => 'sportsclassic',
		'hash' => `jb7002`,
		'shop' => 'pdm',
	),
	'jester2' => array(
		'name' => 'Jester Racecar',
		'brand' => 'Dinka',
		'model' => 'jester2',
		'price' => 210000,
		'category' => 'sports',
		'hash' => `jester2`,
		'shop' => 'pdm',
	),
	'journey' => array(
		'name' => 'Journey',
		'brand' => 'Zirconium',
		'model' => 'journey',
		'price' => 6500,
		'category' => 'vans',
		'hash' => `journey`,
		'shop' => 'pdm',
	),
	'jugular' => array(
		'name' => 'Jugular',
		'brand' => 'Ocelot',
		'model' => 'jugular',
		'price' => 80000,
		'category' => 'sports',
		'hash' => `jugular`,
		'shop' => 'pdm',
	),
	'kalahari' => array(
		'name' => 'Kalahari',
		'brand' => 'Canis',
		'model' => 'kalahari',
		'price' => 14000,
		'category' => 'offroad',
		'hash' => `kalahari`,
		'shop' => 'pdm',
	),
	'kamacho' => array(
		'name' => 'Kamacho',
		'brand' => 'Canis',
		'model' => 'kamacho',
		'price' => 50000,
		'category' => 'offroad',
		'hash' => `kamacho`,
		'shop' => 'pdm',
	),
	'kanjo' => array(
		'name' => 'Blista Kanjo',
		'brand' => 'Dinka',
		'model' => 'kanjo',
		'price' => 12000,
		'category' => 'compacts',
		'hash' => `kanjo`,
		'shop' => 'pdm',
	),
	'komoda' => array(
		'name' => 'Komoda',
		'brand' => 'Lampadati',
		'model' => 'komoda',
		'price' => 55000,
		'category' => 'sports',
		'hash' => `komoda`,
		'shop' => 'pdm',
	),
	'krieger' => array(
		'name' => 'Krieger',
		'brand' => 'Benefactor',
		'model' => 'krieger',
		'price' => 222000,
		'category' => 'super',
		'hash' => `krieger`,
		'shop' => 'pdm',
	),
	'landstalker2' => array(
		'name' => 'Landstalker XL',
		'brand' => 'Dundreary',
		'model' => 'landstalker2',
		'price' => 26000,
		'category' => 'suvs',
		'hash' => `landstalker2`,
		'shop' => 'pdm',
	),
	'le7b' => array(
		'name' => 'RE-7B',
		'brand' => 'Annis',
		'model' => 'le7b',
		'price' => 260000,
		'category' => 'super',
		'hash' => `le7b`,
		'shop' => 'pdm',
	),
	'lectro' => array(
		'name' => 'Lectro',
		'brand' => 'Principe',
		'model' => 'lectro',
		'price' => 28000,
		'category' => 'motorcycles',
		'hash' => `lectro`,
		'shop' => 'pdm',
	),
	'locust' => array(
		'name' => 'Locust',
		'brand' => 'Ocelot',
		'model' => 'locust',
		'price' => 200000,
		'category' => 'sports',
		'hash' => `locust`,
		'shop' => 'pdm',
	),
	'lurcher' => array(
		'name' => 'Gauntlet Classic Custom',
		'brand' => 'Bravado',
		'model' => 'lurcher',
		'price' => 21000,
		'category' => 'muscle',
		'hash' => `lurcher`,
		'shop' => 'pdm',
	),
	'manana' => array(
		'name' => 'Manana',
		'brand' => 'Albany',
		'model' => 'manana',
		'price' => 12800,
		'category' => 'muscle',
		'hash' => `manana`,
		'shop' => 'pdm',
	),
	'manana2' => array(
		'name' => 'Manana Custom',
		'brand' => 'Albany',
		'model' => 'manana2',
		'price' => 24000,
		'category' => 'muscle',
		'hash' => `manana2`,
		'shop' => 'pdm',
	),
	'manchez' => array(
		'name' => 'Manchez',
		'brand' => 'Maibatsu',
		'model' => 'manchez',
		'price' => 8300,
		'category' => 'motorcycles',
		'hash' => `manchez`,
		'shop' => 'pdm',
	),
	'manchez2' => array(
		'name' => 'Manchez',
		'brand' => 'Maibatsu',
		'model' => 'manchez2',
		'price' => 14000,
		'category' => 'motorcycles',
		'hash' => `manchez2`,
		'shop' => 'pdm',
	),
	'massacro2' => array(
		'name' => 'Massacro Racecar',
		'brand' => 'Dewbauchee',
		'model' => 'massacro2',
		'price' => 80000,
		'category' => 'sports',
		'hash' => `massacro2`,
		'shop' => 'pdm',
	),
	'mesa' => array(
		'name' => 'Mesa',
		'brand' => 'Canis',
		'model' => 'mesa',
		'price' => 12000,
		'category' => 'offroad',
		'hash' => `mesa`,
		'shop' => 'pdm',
	),
	'mesa3' => array(
		'name' => 'Mesa Merryweather',
		'brand' => 'Canis',
		'model' => 'mesa3',
		'price' => 400000,
		'category' => 'offroad',
		'hash' => `mesa3`,
		'shop' => 'pdm',
	),
	'michelli' => array(
		'name' => 'Michelli GT',
		'brand' => 'Lampadati',
		'model' => 'michelli',
		'price' => 30000,
		'category' => 'sportsclassic',
		'hash' => `michelli`,
		'shop' => 'pdm',
	),
	'minivan' => array(
		'name' => 'Minivan',
		'brand' => 'Vapid',
		'model' => 'minivan',
		'price' => 7000,
		'category' => 'vans',
		'hash' => `minivan`,
		'shop' => 'pdm',
	),
	'minivan2' => array(
		'name' => 'Minivan Custom',
		'brand' => 'Vapid',
		'model' => 'minivan2',
		'price' => 10000,
		'category' => 'vans',
		'hash' => `minivan2`,
		'shop' => 'pdm',
	),
	'moonbeam2' => array(
		'name' => 'Moonbeam Custom',
		'brand' => 'Declasse',
		'model' => 'moonbeam2',
		'price' => 15000,
		'category' => 'vans',
		'hash' => `moonbeam2`,
		'shop' => 'pdm',
	),
	'nebula' => array(
		'name' => 'Nebula',
		'brand' => 'Vulcar',
		'model' => 'nebula',
		'price' => 22000,
		'category' => 'sportsclassic',
		'hash' => `nebula`,
		'shop' => 'pdm',
	),
	'neo' => array(
		'name' => 'Neo',
		'brand' => 'Vysser',
		'model' => 'neo',
		'price' => 230000,
		'category' => 'sports',
		'hash' => `neo`,
		'shop' => 'pdm',
	),
	'nero2' => array(
		'name' => 'Nero Custom',
		'brand' => 'Truffade',
		'model' => 'nero2',
		'price' => 260000,
		'category' => 'super',
		'hash' => `nero2`,
		'shop' => 'pdm',
	),
	'novak' => array(   
		'name' => 'Novak',
		'brand' => 'Lampadati',
		'model' => 'novak',
		'price' => 70000,
		'category' => 'suvs',
		'hash' => `novak`,
		'shop' => 'pdm',
	),
	'oppressor' => array(
		'name' => 'Oppressor',
		'brand' => 'Pegassi',
		'model' => 'oppressor',
		'price' => 9999999,
		'category' => 'super',
		'hash' => `oppressor`,
		'shop' => 'pdm',
	),
	'outlaw' => array(
		'name' => 'Outlaw',
		'brand' => 'Nagasaki',
		'model' => 'outlaw',
		'price' => 15000,
		'category' => 'offroad',
		'hash' => `outlaw`,
		'shop' => 'pdm',
	),
	'paradise' => array(
		'name' => 'Paradise',
		'brand' => 'Bravado',
		'model' => 'paradise',
		'price' => 9000,
		'category' => 'vans',
		'hash' => `paradise`,
		'shop' => 'pdm',
	),
	'paragon' => array(
		'name' => 'Paragon',
		'brand' => 'Enus',
		'model' => 'paragon',
		'price' => 60000,
		'category' => 'sports',
		'hash' => `paragon`,
		'shop' => 'pdm',
	),
	'penumbra' => array(
		'name' => 'Penumbra',
		'brand' => 'Maibatsu',
		'model' => 'penumbra',
		'price' => 22000,
		'category' => 'sports',
		'hash' => `penumbra`,
		'shop' => 'pdm',
	),
	'penumbra2' => array(
		'name' => 'Penumbra FF',
		'brand' => 'Maibatsu',
		'model' => 'penumbra2',
		'price' => 30000,
		'category' => 'sports',
		'hash' => `penumbra2`,
		'shop' => 'pdm',
	),
	'peyote' => array(
		'name' => 'Peyote',
		'brand' => 'Vapid',
		'model' => 'peyote',
		'price' => 23500,
		'category' => 'sportsclassic',
		'hash' => `peyote`,
		'shop' => 'pdm',
	),
	'peyote2' => array(
		'name' => 'Peyote Gasser',
		'brand' => 'Vapid',
		'model' => 'peyote2',
		'price' => 40000,
		'category' => 'sportsclassic',
		'hash' => `peyote2`,
		'shop' => 'pdm',
	),
	'peyote3' => array(
		'name' => 'Peyote Custom',
		'brand' => 'Vapid',
		'model' => 'peyote3',
		'price' => 48000,
		'category' => 'sportsclassic',
		'hash' => `peyote3`,
		'shop' => 'pdm',
	),
	'primo' => array(
		'name' => 'Primo',
		'brand' => 'Albany',
		'model' => 'primo',
		'price' => 5000,
		'category' => 'sedans',
		'hash' => `primo`,
		'shop' => 'pdm',
	),
	'rancherxl' => array(
		'name' => 'Rancher XL',
		'brand' => 'Declasse',
		'model' => 'rancherxl',
		'price' => 24000,
		'category' => 'offroad',
		'hash' => `rancherxl`,
		'shop' => 'pdm',
	),
	'raptor' => array(
		'name' => 'Raptor',
		'brand' => 'BF',
		'model' => 'raptor',
		'price' => 90000,
		'category' => 'sports',
		'hash' => `raptor`,
		'shop' => 'pdm',
	),
	'ratbike' => array(
		'name' => 'Rat Bike',
		'brand' => 'Western',
		'model' => 'ratbike',
		'price' => 3000,
		'category' => 'motorcycles',
		'hash' => `ratbike`,
		'shop' => 'pdm',
	),
	'rebla' => array(
		'name' => 'Rebla GTS',
		'brand' => 'Übermacht',
		'model' => 'rebla',
		'price' => 21000,
		'category' => 'suvs',
		'hash' => `rebla`,
		'shop' => 'pdm',
	),
	'retinue' => array(
		'name' => 'Retinue',
		'brand' => 'Vapid',
		'model' => 'retinue',
		'price' => 32000,
		'category' => 'sportsclassic',
		'hash' => `retinue`,
		'shop' => 'pdm',
	),
	'retinue2' => array(
		'name' => 'Retinue MKII',
		'brand' => 'Vapid',
		'model' => 'retinue2',
		'price' => 38000,
		'category' => 'sportsclassic',
		'hash' => `retinue2`,
		'shop' => 'pdm',
	),
	'riata' => array(
		'name' => 'Riata',
		'brand' => 'Vapid',
		'model' => 'riata',
		'price' => 380000,
		'category' => 'offroad',
		'hash' => `riata`,
		'shop' => 'pdm',
	),
	'ruiner' => array(
		'name' => 'Ruiner',
		'brand' => 'Imponte',
		'model' => 'ruiner',
		'price' => 29000,
		'category' => 'muscle',
		'hash' => `ruiner`,
		'shop' => 'pdm',
	),
	'ruiner2' => array(
		'name' => 'Ruiner 2000',
		'brand' => 'Imponte',
		'model' => 'ruiner2',
		'price' => 50000,
		'category' => 'muscle',
		'hash' => `ruiner2`,
		'shop' => 'pdm',
	),
	'rumpo3' => array(
		'name' => 'Rumpo Custom',
		'brand' => 'Bravado',
		'model' => 'rumpo3',
		'price' => 19500,
		'category' => 'vans',
		'hash' => `rumpo3`,
		'shop' => 'pdm',
	),
	's80' => array(
		'name' => 'S80RR',
		'brand' => 'Annis',
		'model' => 's80',
		'price' => 205000,
		'category' => 'super',
		'hash' => `s80`,
		'shop' => 'pdm',
	),
	'sadler' => array(
		'name' => 'Sadler',
		'brand' => 'Vapid',
		'model' => 'sadler',
		'price' => 20000,
		'category' => 'offroad',
		'hash' => `sadler`,
		'shop' => 'pdm',
	),
	'sanchez' => array(
		'name' => 'Sanchez Livery',
		'brand' => 'Maibatsu',
		'model' => 'sanchez',
		'price' => 5300,
		'category' => 'motorcycles',
		'hash' => `sanchez`,
		'shop' => 'pdm',
	),
	'sanchez2' => array(
		'name' => 'Sanchez',
		'brand' => 'Maibatsu',
		'model' => 'sanchez2',
		'price' => 5300,
		'category' => 'motorcycles',
		'hash' => `sanchez2`,
		'shop' => 'pdm',
	),
	'sanctus' => array(
		'name' => 'Sanctus',
		'brand' => 'LCC',
		'model' => 'sanctus',
		'price' => 35000,
		'category' => 'motorcycles',
		'hash' => `sanctus`,
		'shop' => 'pdm',
	),
	'sandking2' => array(
		'name' => 'Sandking SWB', 
		'brand' => 'Annis',
		'price' => 38000,
		'category' => 'offroad',
		'model' => 'sandking2',
		'hash' => `sandking2`,
		'shop' => 'pdm',
	),
	'savestra' => array(
		'name' => 'Savestra',
		'brand' => 'Annis',
		'model' => 'savestra',
		'price' => 67000,
		'category' => 'sportsclassic',
		'hash' => `savestra`,
		'shop' => 'pdm',
	),
	'schafter4' => array(
		'name' => 'Schafter LWB',
		'brand' => 'Benefactor',
		'model' => 'schafter4',
		'price' => 21000,
		'category' => 'sports',
		'hash' => `schafter4`,
		'shop' => 'pdm',
	),
	'schlagen' => array(
		'name' => 'Schlagen GT',
		'brand' => 'Benefactor',
		'model' => 'schlagen',
		'price' => 160000,
		'category' => 'sports',
		'hash' => `schlagen`,
		'shop' => 'pdm',
	),
	'schwarzer' => array(
		'name' => 'Schwartzer',
		'brand' => 'Benefactor',
		'model' => 'schwarzer',
		'price' => 47000,
		'category' => 'sports',
		'hash' => `schwarzer`,
		'shop' => 'pdm',
	),
	'scorcher' => array(
		'name' => 'Scorcher',
		'model' => 'scorcher',
		'price' => 280,
		'category' => 'cycles',
		'hash' => `scorcher`,
		'shop' => 'pdm',
	),
	'seminole2' => array(
		'name' => 'Seminole Frontier',
		'brand' => 'Canis',
		'model' => 'seminole2',
		'price' => 13000,
		'category' => 'suvs',
		'hash' => `seminole2`,
		'shop' => 'pdm',
	),
	'serrano' => array(
		'name' => 'Serrano',
		'brand' => 'Benefactor',
		'model' => 'serrano',
		'price' => 48000,
		'category' => 'suvs',
		'hash' => `serrano`,
		'shop' => 'pdm',
	),
	'sheava' => array(
		'name' => 'ETR1',
		'brand' => 'Emperor',
		'model' => 'sheava',
		'price' => 220000,
		'category' => 'super',
		'hash' => `sheava`,
		'shop' => 'pdm',
	),
	'shotaro' => array(
		'name' => 'Shotaro Concept',
		'brand' => 'Nagasaki',
		'model' => 'shotaro',
		'price' => 320000,
		'category' => 'motorcycles',
		'hash' => `shotaro`,
		'shop' => 'pdm',
	),
	'slamtruck' => array(
		'name' => 'Slam Truck',
		'brand' => 'Vapid',
		'model' => 'slamtruck',
		'price' => 100000,
		'category' => 'muscle',
		'hash' => `slamtruck`,
		'shop' => 'pdm',
	),
	'slamvan' => array(
		'name' => 'Slam Van',
		'brand' => 'Vapid',
		'model' => 'slamvan',
		'price' => 30000,
		'category' => 'muscle',
		'hash' => `slamvan`,
		'shop' => 'pdm',
	),
	'slamvan2' => array(
		'name' => 'Lost Slam Van',
		'brand' => 'Vapid',
		'model' => 'slamvan2',
		'price' => 90000,
		'category' => 'muscle',
		'hash' => `slamvan2`,
		'shop' => 'pdm',
	),
	'speedo' => array(
		'name' => 'Speedo',
		'brand' => 'Vapid',
		'model' => 'speedo',
		'price' => 10000,
		'category' => 'vans',
		'hash' => `speedo`,
		'shop' => 'pdm',
	),
	'speedo4' => array(
		'name' => 'Speedo Custom',
		'brand' => 'Vapid',
		'model' => 'speedo4',
		'price' => 15000,
		'category' => 'vans',
		'hash' => `speedo4`,
		'shop' => 'pdm',
	),
	'stalion2' => array(
		'name' => 'Stallion Burgershot',
		'brand' => 'Declasse',
		'model' => 'stalion2',
		'price' => 40000,
		'category' => 'muscle',
		'hash' => `stalion2`,
		'shop' => 'pdm',
	),
	'stanier' => array(
		'name' => 'Stanier',
		'brand' => 'Vapid',
		'model' => 'stanier',
		'price' => 19000,
		'category' => 'sedans',
		'hash' => `stanier`,
		'shop' => 'pdm',
	),
	'stinger' => array(
		'name' => 'Stinger',
		'brand' => 'Grotti',
		'model' => 'stinger',
		'price' => 39500,
		'category' => 'sportsclassic',
		'hash' => `stinger`,
		'shop' => 'pdm',
	),
	'stratum' => array(
		'name' => 'Stratum',
		'brand' => 'Zirconium',
		'model' => 'stratum',
		'price' => 15000,
		'category' => 'sedans',
		'hash' => `stratum`,
		'shop' => 'pdm',
	),
	'stretch' => array(
		'name' => 'Stretch',
		'brand' => 'Dundreary',
		'model' => 'stretch',
		'price' => 19000,
		'category' => 'sedans',
		'hash' => `stretch`,
		'shop' => 'pdm',
	),
	'stromberg' => array(
		'name' => 'Stromberg',
		'brand' => 'Ocelot',
		'model' => 'stromberg',
		'price' => 80000,
		'category' => 'sportsclassic',
		'hash' => `stromberg`,
		'shop' => 'pdm',
	),
	'stryder' => array(
		'name' => 'Stryder',
		'brand' => 'Nagasaki',
		'model' => 'stryder',
		'price' => 50000,
		'category' => 'motorcycles',
		'hash' => `stryder`,
		'shop' => 'pdm',
	),
	'sugoi' => array(
		'name' => 'Sugoi',
		'brand' => 'Dinka',
		'model' => 'sugoi',
		'price' => 85000,
		'category' => 'sports',
		'hash' => `sugoi`,
		'shop' => 'pdm',
	),
	'sultan2' => array(
		'name' => 'Sultan Custom',
		'brand' => 'Karin',
		'model' => 'sultan2',
		'price' => 55000,
		'category' => 'sports',
		'hash' => `sultan2`,
		'shop' => 'pdm',
	),
	'surfer' => array(
		'name' => 'Surfer',
		'brand' => 'BF',
		'model' => 'surfer',
		'price' => 9000,
		'category' => 'vans',
		'hash' => `surfer`,
		'shop' => 'pdm',
	),
	'swinger' => array(
		'name' => 'Swinger',
		'brand' => 'Ocelot',
		'model' => 'swinger',
		'price' => 221000,
		'category' => 'sportsclassic',
		'hash' => `swinger`,
		'shop' => 'pdm',
	),
	'thrax' => array(
		'name' => 'Thrax',
		'brand' => 'Truffade',
		'model' => 'thrax',
		'price' => 180000,
		'category' => 'super',
		'hash' => `thrax`,
		'shop' => 'pdm',
	),
	'tigon' => array(
		'name' => 'Tigon',
		'brand' => 'Lampadati',
		'model' => 'tigon',
		'price' => 240000,
		'category' => 'super',
		'hash' => `tigon`,
		'shop' => 'pdm',
	),
	'toreador' => array(
		'name' => 'Toreador',
		'brand' => 'Pegassi',
		'model' => 'toreador',
		'price' => 50000,
		'category' => 'sportsclassic',
		'hash' => `toreador`,
		'shop' => 'pdm',
	),
	'tornado' => array(
		'name' => 'Tornado',
		'brand' => 'Declasse',
		'model' => 'tornado',
		'price' => 21000,
		'category' => 'sportsclassic',
		'hash' => `tornado`,
		'shop' => 'pdm',
	),
	'tornado2' => array(
		'name' => 'Tornado Gang',
		'brand' => 'Declasse',
		'model' => 'tornado2',
		'price' => 22000,
		'category' => 'sportsclassic',
		'hash' => `tornado2`,
		'shop' => 'pdm',
	),
	'tornado5' => array(
		'name' => 'Tornado Custom',
		'brand' => 'Declasse',
		'model' => 'tornado5',
		'price' => 22000,
		'category' => 'sportsclassic',
		'hash' => `tornado5`,
		'shop' => 'pdm',
	),
	'toros' => array(
		'name' => 'Toros',
		'brand' => 'Pegassi',
		'model' => 'toros',
		'price' => 65000,
		'category' => 'suvs',
		'hash' => `toros`,
		'shop' => 'pdm',
	),
	'tribike' => array(
		'name' => 'Tri Bike',
		'model' => 'tribike',
		'price' => 500,
		'category' => 'cycles',
		'hash' => `tribike`,
		'shop' => 'pdm',
	),
	'tribike2' => array(
		'name' => 'Tri Bike 2',
		'model' => 'tribike2',
		'price' => 700,
		'category' => 'cycles',
		'hash' => `tribike2`,
		'shop' => 'pdm',
	),
	'tribike3' => array(
		'name' => 'Tri Bike 3',
		'model' => 'tribike3',
		'price' => 520,
		'category' => 'cycles',
		'hash' => `tribike3`,
		'shop' => 'pdm',
	),
	'tropos' => array(
		'name' => 'Tropos Rallye',
		'brand' => 'Lampadati',
		'model' => 'tropos',
		'price' => 65000,
		'category' => 'sports',
		'hash' => `tropos`,
		'shop' => 'pdm',
	),
	'tulip' => array(
		'name' => 'Tulip',
		'brand' => 'Declasse',
		'model' => 'tulip',
		'price' => 80000,
		'category' => 'muscle',
		'hash' => `tulip`,
		'shop' => 'pdm',
	),
	'turismo2' => array(
		'name' => 'Turismo Classic',
		'brand' => 'Grotti',
		'model' => 'turismo2',
		'price' => 170000,
		'category' => 'sportsclassic',
		'hash' => `turismo2`,
		'shop' => 'pdm',
	),
	'tyrus' => array(
		'name' => 'Tyrus',
		'brand' => 'Progen',
		'model' => 'tyrus',
		'price' => 230000,
		'category' => 'super',
		'hash' => `tyrus`,
		'shop' => 'pdm',
	),
	'vader' => array(
		'name' => 'Vader',
		'brand' => 'Shitzu',
		'model' => 'vader',
		'price' => 7200,
		'category' => 'motorcycles',
		'hash' => `vader`,
		'shop' => 'pdm',
	),
	'vagrant' => array(
		'name' => 'Vagrant', 
		'brand' => 'Maxwell',
		'price' => 50000,
		'category' => 'offroad',
		'model' => 'vagrant',
		'hash' => `vagrant`,
		'shop' => 'pdm',
	),
	'vamos' => array(
		'name' => 'Vamos',
		'brand' => 'Declasse',
		'model' => 'vamos',
		'price' => 30000,
		'category' => 'muscle',
		'hash' => `vamos`,
		'shop' => 'pdm',
	),
	'verus' => array(
		'name' => 'Verus', 
		'brand' => 'Dinka',
		'price' => 20000,
		'category' => 'offroad',
		'model' => 'verus',
		'hash' => `verus`,
		'shop' => 'pdm',
	),
	'vindicator' => array(
		'name' => 'Vindicator',
		'brand' => 'Dinka',
		'model' => 'vindicator',
		'price' => 19000,
		'category' => 'motorcycles',
		'hash' => `vindicator`,
		'shop' => 'pdm',
	),
	'virgo2' => array(
		'name' => 'Virgo Custom Classic',
		'brand' => 'Dundreary',
		'model' => 'virgo2',
		'price' => 21000,
		'category' => 'muscle',
		'hash' => `virgo2`,
		'shop' => 'pdm',
	),
	'viseris' => array(
		'name' => 'Viseris',
		'brand' => 'Lampadati',
		'model' => 'viseris',
		'price' => 210000,
		'category' => 'sportsclassic',
		'hash' => `viseris`,
		'shop' => 'pdm',
	),
	'voltic2' => array(
		'name' => 'Rocket Voltic',
		'brand' => 'Coil',
		'model' => 'voltic2',
		'price' => 9830400,
		'category' => 'super',
		'hash' => `voltic2`,
		'shop' => 'pdm',
	),
	'vortex' => array(
		'name' => 'Vortex',
		'brand' => 'Pegassi',
		'model' => 'vortex',
		'price' => 31000,
		'category' => 'motorcycles',
		'hash' => `vortex`,
		'shop' => 'pdm',
	),
	'vstr' => array(
		'name' => 'V-STR',
		'brand' => 'Albany',
		'model' => 'vstr',
		'price' => 80000,
		'category' => 'sports',
		'hash' => `vstr`,
		'shop' => 'pdm',
	),
	'warrener' => array(
		'name' => 'Warrener',
		'brand' => 'Vulcar',
		'model' => 'warrener',
		'price' => 4000,
		'category' => 'sedans',
		'hash' => `warrener`,
		'shop' => 'pdm',
	),
	'weevil' => array(
		'name' => 'Weevil',
		'brand' => 'BF',
		'model' => 'weevil',
		'price' => 9000,
		'category' => 'compacts',
		'hash' => `weevil`,
		'shop' => 'pdm',
	),
	'winky' => array(
		'name' => 'Winky', 
		'brand' => 'Vapid',
		'price' => 10000,
		'category' => 'offroad',
		'model' => 'winky',
		'hash' => `winky`,
		'shop' => 'pdm',
	),
	'wolfsbane' => array(
		'name' => 'Wolfsbane',
		'brand' => 'Western',
		'model' => 'wolfsbane',
		'price' => 14000,
		'category' => 'motorcycles',
		'hash' => `wolfsbane`,
		'shop' => 'pdm',
	),
	'yosemite2' => array(
		'name' => 'Yosemite Drift',
		'brand' => 'Declasse',
		'model' => 'yosemite2',
		'price' => 55000,
		'category' => 'muscle',
		'hash' => `yosemite2`,
		'shop' => 'pdm',
	),
	'yosemite3' => array(
		'name' => 'Yosemite Rancher', 
		'brand' => 'Declasse',
		'price' => 425000,
		'category' => 'offroad',
		'model' => 'yosemite3',
		'hash' => `yosemite3`,
		'shop' => 'pdm',
	),
	'youga' => array(
		'name' => 'Youga',
		'brand' => 'Bravado',
		'model' => 'youga',
		'price' => 8000,
		'category' => 'vans',
		'hash' => `youga`,
		'shop' => 'pdm',
	),
	'youga2' => array(
		'name' => 'Youga Classic',
		'brand' => 'Bravado',
		'model' => 'youga2',
		'price' => 14500,
		'category' => 'vans',
		'hash' => `youga2`,
		'shop' => 'pdm',
	),
	'youga3' => array(
		'name' => 'Youga Classic 4x4',
		'brand' => 'Bravado',
		'model' => 'youga3',
		'price' => 15000,
		'category' => 'vans',
		'hash' => `youga3`,
		'shop' => 'pdm',
	),
	'zion3' => array(
		'name' => 'Zion Classic',
		'brand' => 'Übermacht',
		'model' => 'zion3',
		'price' => 45000,
		'category' => 'sportsclassic',
		'hash' => `zion3`,
		'shop' => 'pdm',
	),
	'zombiea' => array(
		'name' => 'Zombie Bobber',
		'brand' => 'Western',
		'model' => 'zombiea',
		'price' => 28000,
		'category' => 'motorcycles',
		'hash' => `zombiea`,
		'shop' => 'pdm',
	),
	'zorrusso' => array(
		'name' => 'Zorrusso',
		'brand' => 'Pegassi',
		'model' => 'zorrusso',
		'price' => 277000,
		'category' => 'super',
		'hash' => `zorrusso`,
		'shop' => 'pdm',
	),
	'comet6' => array(
		'name' => 'Comet S2',
		'brand' => 'Pfister',
		'model' => 'comet6',
		'price' => 230000,
		'category' => 'sports',
		'hash' => `comet6`,
		'shop' => 'pdm',
	),
	'remus' => array(
		'name' => 'Remus',
		'brand' => 'Annis',
		'model' => 'remus',
		'price' => 48000,
		'category' => 'sports',
		'hash' => `remus`,
		'shop' => 'pdm',
	),
	'jester4' => array(
		'name' => 'Jester RR',
		'brand' => 'Dinka',
		'model' => 'jester4',
		'price' => 240000,
		'category' => 'sports',
		'hash' => `jester4`,
		'shop' => 'pdm',
	),
	'tailgater2' => array(
		'name' => 'Tailgater S',
		'brand' => 'Obey',
		'model' => 'tailgater2',
		'price' => 51000,
		'category' => 'sedans',
		'hash' => `tailgater2`,
		'shop' => 'pdm',
	),
	'warrener2' => array(
		'name' => 'Warrener HKR',
		'brand' => 'Vulcar',
		'model' => 'warrener2',
		'price' => 30000,
		'category' => 'sedans',
		'hash' => `warrener2`,
		'shop' => 'pdm',
	),
	'rt3000' => array(
		'name' => 'RT3000',
		'brand' => 'Dinka',
		'model' => 'rt3000',
		'price' => 65000,
		'category' => 'sports',
		'hash' => `rt3000`,
		'shop' => 'pdm',
	),
	'zr350' => array(
		'name' => 'ZR350',
		'brand' => 'Annis',
		'model' => 'zr350',
		'price' => 38000,
		'category' => 'sports',
		'hash' => `zr350`,
		'shop' => 'pdm',
	),
	'dominator7' => array(
		'name' => 'Dominator ASP',
		'brand' => 'Vapid',
		'model' => 'dominator7',
		'price' => 110000,
		'category' => 'muscle',
		'hash' => `dominator7`,
		'shop' => 'pdm',
	),
	'dominator8' => array(
		'name' => 'Dominator GTT',
		'brand' => 'Vapid',
		'model' => 'dominator8',
		'price' => 80000,
		'category' => 'muscle',
		'hash' => `dominator8`,
		'shop' => 'pdm',
	),
	'euros' => array(
		'name' => 'Euros',
		'brand' => 'Annis',
		'model' => 'euros',
		'price' => 80000,
		'category' => 'sports',
		'hash' => `euros`,
		'shop' => 'pdm',
	),
	'futo2' => array(
		'name' => 'Futo GTX',
		'brand' => 'Karin',
		'model' => 'futo2',
		'price' => 39000,
		'category' => 'sports',
		'hash' => `futo2`,
		'shop' => 'pdm',
	),
	'calico' => array(
		'name' => 'Calico GTF',
		'brand' => 'Karin',
		'model' => 'calico',
		'price' => 39000,
		'category' => 'sports',
		'hash' => `calico`,
		'shop' => 'pdm',
	),
	'sultan3' => array(
		'name' => 'Sultan Classic Custom',
		'brand' => 'Karin',
		'model' => 'sultan3',
		'price' => 56000,
		'category' => 'sports',
		'hash' => `sultan3`,
		'shop' => 'pdm',
	),
	'vectre' => array(
		'name' => 'Emperor Vectre',
		'brand' => 'Emperor',
		'model' => 'vectre',
		'price' => 80000,
		'category' => 'sports',
		'hash' => `vectre`,
		'shop' => 'pdm',
	),
	'growler' => array(
		'name' => 'Growler',
		'brand' => 'Pfister',
		'model' => 'growler',
		'price' => 205000,
		'category' => 'sports',
		'hash' => `growler`,
		'shop' => 'pdm',
	),
	'cypher' => array(
		'name' => 'Cypher',
		'brand' => 'Ubermacht',
		'model' => 'cypher',
		'price' => 155000,
		'category' => 'sports',
		'hash' => `cypher`,
		'shop' => 'pdm',
	),
	'previon' => array(
		'name' => 'Previon',
		'brand' => 'Karin',
		'model' => 'previon',
		'price' => 149000,
		'category' => 'coupes',
		'hash' => `previon`,
		'shop' => 'pdm',
    ),
);

$sort = array('category', 'shop', 'price');

parse(print_r(sortArray($array, $sort)));